// ==================== i18n SYSTEM ====================
const i18n = {
  languages: {
    en: { flag: "🇬🇧", label: "EN" },
    tr: { flag: "🇹🇷", label: "TR" },
    th: { flag: "🇹🇭", label: "TH" },
  },

  translations: {
    en: {
      // Splash
      splash_tagline: "same questions. blind answers. one reveal.",
      splash_get_started: "get started",
      splash_have_account: "i have an account",
      // Guest Auth
      guest_invited: "you've been invited! 🎉",
      guest_title: "join the game",
      guest_subtitle: "enter a display name to start playing",
      guest_placeholder: "your name...",
      guest_play: "play as guest",
      guest_have_account: "i have an account",
      guest_error_min_chars: "at least 2 characters",
      guest_error_connection: "connection error, try again",
      // Onboarding
      onboarding_title: "how it works",
      onboarding_step1_title: "pick a pack",
      onboarding_step1_desc: "choose a question pack that matches your vibe",
      onboarding_step2_title: "answer privately",
      onboarding_step2_desc:
        "both of you answer the same questions — no peeking",
      onboarding_step3_title: "reveal together",
      onboarding_step3_desc: "answers unlock only when you've both submitted",
      onboarding_cta: "let's go",
      // Home
      home_all: "All",
      home_active: "Active",
      home_completed: "Completed",
      home_invite_sent: "invite sent",
      home_new_session: "+ new session",
      home_loading: "loading...",
      home_no_sessions: "no sessions yet — start one!",
      home_with: "with",
      home_waiting_partner: "waiting for partner",
      home_done: "done",
      home_load_error: "could not load sessions",
      home_show_more: "Show more",
      home_with_alex: "with Alex",
      home_with_jordan: "with Jordan",
      home_with_taylor_match: "with Taylor · 83% match",
      badge_reveal: "Reveal!",
      badge_progress: "In progress",
      badge_waiting: "Waiting",
      // Pack names
      pack_couples: "Couples Edition",
      pack_bestfriends: "Best Friends",
      pack_deeptalk: "Deep Talk",
      pack_36questions: "36 Questions to Fall in Love",
      pack_friendship_deep_dive: "Friendship Deep Dive",
      // Pack counts
      pack_count_couples: "10 questions",
      pack_count_bestfriends: "10 questions",
      pack_count_deeptalk: "10 questions",
      pack_count_36questions: "36 questions · based on Arthur Aron's study",
      pack_hottakes: "Hot Takes",
      pack_redflags: "Red Flag or Nah",
      pack_chaotic: "Chaotic Energy",
      pack_strangervibes: "Stranger Vibes",
      pack_count_hottakes: "10 questions · spicy opinions only",
      pack_count_redflags: "10 questions · judge freely",
      pack_count_chaotic: "10 questions · unhinged vibes",
      pack_count_strangervibes: "15 questions · terminally online energy",
      pack_desc_strangervibes:
        "memes, chaos & zero filter. made for strangers who get it.",
      pack_drunkconfessions: "Drunk Confessions",
      pack_count_drunkconfessions: "15 questions · liquid courage edition",
      pack_desc_drunkconfessions:
        "the things you'd only say after a few drinks. no filter, no regrets.",
      pack_fungames: "Fun & Games",
      pack_worldtaste: "World & Taste",
      pack_cinematastes: "Cinema Tastes",
      pack_cinemascenes: "Iconic Scenes",
      pack_cinemadebates: "Cinema Debates",
      pack_ethics: "Ethics & Dilemmas",
      pack_situations: "Situations",
      pack_cuisine: "Cuisine Match",
      pack_livingtogether: "Living Together",
      pack_soulspirit: "Soul & Spirit",
      pack_count_fungames: "10 questions · lighthearted fun",
      pack_count_worldtaste: "10 questions · culture & flavors",
      pack_count_cinematastes:
        "12 questions · genres, snacks & guilty pleasures",
      pack_count_cinemascenes: "12 questions · iconic moments & characters",
      pack_count_cinemadebates: "12 questions · hot takes on cinema",
      pack_count_ethics: "10 questions · moral crossroads",
      pack_count_situations: "10 questions · react to life",
      pack_count_cuisine: "15 questions · food & flavor compatibility",
      pack_count_livingtogether: "10 questions · cohabitation vibes",
      pack_count_soulspirit: "10 questions · meaning & belief",
      pack_desc_fungames: "lighthearted chaos. no wrong answers.",
      pack_desc_worldtaste: "travel, food, culture — how worldly are you?",
      pack_desc_cinematastes:
        "genres, directors, guilty pleasures — do you actually watch the same stuff?",
      pack_desc_cinemascenes:
        "villains, plot twists, movie deaths — relive the moments that shaped you",
      pack_desc_cinemadebates:
        "subtitles vs dubbed, sequels, spoilers — settle the cinema arguments once and for all",
      pack_desc_cuisine:
        "spice levels, comfort carbs, food deal-breakers — are you actually compatible?",
      pack_desc_situations: "real-life moments. how would you actually react?",
      // Nav
      nav_home: "Home",
      nav_packs: "Decks",
      // Packs
      packs_subtitle: "pick one, send it, see what happens",
      packs_trending: "trending now",
      packs_all: "all packs",
      packs_played: "played",
      // Pack descriptions (featured cards)
      pack_desc_36questions:
        "the viral study that makes strangers fall in love. are you brave enough?",
      pack_desc_hottakes: "spicy opinions only. no fence-sitting allowed.",
      pack_desc_redflags: "judge each other's takes. no mercy.",
      // Category filters
      cat_all: "All",
      cat_love: "Love",
      cat_friends: "Friends",
      cat_spicy: "Spicy",
      cat_deep: "Deep",
      cat_culture: "Culture",
      cat_lifestyle: "Lifestyle",
      cat_self: "Self",
      // Collections
      packs_collections: "collections",
      coll_decks: "decks",
      coll_date_night: "Date Night",
      coll_desc_date_night:
        "the perfect bundle for couples who want to go deeper",
      coll_spicy_edition: "Spicy Edition",
      coll_desc_spicy_edition: "hot takes, red flags & chaos — all in one pack",
      coll_deep_bonds: "Deep Bonds",
      coll_desc_deep_bonds: "meaningful conversations that actually matter",
      coll_friend_zone: "Friend Zone",
      coll_desc_friend_zone: "fun & real talk for you and your bestie",
      coll_culture_taste: "Culture & Taste",
      coll_desc_culture_taste:
        "travel, beliefs & lifestyle — how aligned are you?",
      coll_cinema_night: "Cinema Night",
      coll_desc_cinema_night:
        "genres, iconic scenes & hot takes — are you movie soulmates?",
      coll_know_your_partner: "Know Your Partner",
      coll_desc_know_your_partner:
        "archetype quizzes to take about your partner & share",
      coll_know_yourself: "Know Yourself",
      coll_desc_know_yourself:
        "personality, shadow, boundaries — the full inner deep dive",
      coll_love_decoded: "Love Decoded",
      coll_desc_love_decoded:
        "attachment, love language & your relationship patterns",
      coll_relationship_xray: "Relationship X-Ray",
      coll_desc_relationship_xray:
        "see through the dynamics — couple story, hidden truths & more",
      coll_inner_work: "Inner Work",
      coll_desc_inner_work:
        "stress, sabotage & shadow — the hard stuff that heals",
      // Solo packs
      pack_attachment: "Attachment Style",
      pack_innermirror: "Inner Mirror",
      pack_stresstype: "Stress Response",
      pack_count_attachment: "10 questions · how you love",
      pack_count_innermirror: "10 questions · who you really are",
      pack_count_stresstype: "10 questions · fight, flight, freeze or fawn",
      pack_desc_attachment:
        "discover your attachment style. no partner needed.",
      pack_desc_innermirror: "a mirror into your personality. just you.",
      // Solo results
      solo_badge: "Solo",
      solo_your_result: "your result",
      solo_dominant_trait: "dominant trait",
      solo_breakdown: "full breakdown",
      solo_take_another: "take another test",
      solo_you_probably: "you probably...",
      solo_note_to_self: "note to self",
      mode_partner: "Partner",
      mode_self: "Self",
      // New solo packs
      pack_lovelang: "Love Language",
      pack_shadow: "Shadow Self",
      pack_emotionalage: "Emotional Age",
      pack_boundaries: "Boundary Check",
      pack_selfsabotage: "Self-Sabotage",
      pack_count_lovelang: "10 questions · how you give & receive love",
      pack_count_shadow: "10 questions · what you hide from yourself",
      pack_count_emotionalage: "10 questions · how old is your inner self",
      pack_count_boundaries: "10 questions · walls, filters, or open doors",
      pack_count_selfsabotage: "10 questions · why you get in your own way",
      pack_desc_lovelang:
        "based on the 5 love languages. warning: may cause feelings.",
      pack_desc_emotionalage:
        "not your age — your emotional age. they're rarely the same.",
      // Horoscope packs
      pack_zodiacenergy: "Zodiac Energy",
      pack_moonphase: "Moon Phase",
      pack_cosmiclove: "Cosmic Love Style",
      pack_count_zodiacenergy: "10 questions · fire, earth, air, or water",
      pack_count_moonphase: "10 questions · which moon phase are you",
      pack_count_cosmiclove: "10 questions · how the planets shape your love",
      pack_desc_zodiacenergy:
        "which element runs through your veins? no birth chart needed.",
      pack_desc_moonphase:
        "your personality as a moon phase. warning: eerily accurate.",
      pack_desc_cosmiclove:
        "venus, mars, moon, or jupiter — which planet rules your heart?",
      coll_cosmic_self: "Cosmic Self",
      coll_desc_cosmic_self:
        "zodiac, moon phases & planetary love — your cosmic blueprint",
      // Character archetype decks
      pack_partnertype: "Partner Archetype",
      pack_partnerera: "Partner Era",
      pack_couplestory: "Couple Story",
      pack_whattheyhide: "What They Hide",
      pack_count_partnertype: "10 questions · what type is your person?",
      pack_count_partnerera: "10 questions · what era are you in?",
      pack_count_couplestory: "10 questions · your couple dynamic",
      pack_count_whattheyhide: "10 questions · unspoken truths",
      pack_desc_partnertype:
        "golden retriever or chaos agent? find out their archetype.",
      pack_desc_partnerera:
        "main character, healer, ride or die, or soft villain?",
      pack_desc_couplestory:
        "soulmates, adventure duo, chaos couple, or slow burn?",
      pack_desc_whattheyhide: "the things they feel but never say out loud.",
      // Loyalty pack
      pack_loyalty: "Loyalty Test",
      pack_count_loyalty: "10 questions · trust or bust",
      pack_desc_loyalty:
        "how loyal are you really? scenarios, green flags, and the truth.",
      // Blind Guess packs
      pack_flirtguess: "Flirt & Guess",
      pack_desirematch: "Desire Match",
      pack_count_flirtguess: "10 questions · answer + predict",
      pack_count_desirematch: "10 questions · answer + predict",
      pack_desc_flirtguess:
        "answer honestly. then guess what they said. dare you?",
      pack_desc_desirematch:
        "what you want vs what they want. how well do you really know?",
      coll_blind_guess: "Blind Guess",
      coll_desc_blind_guess:
        "answer for yourself, then predict your partner. double the reveal.",
      // Blind Guess UI
      blindguess_own_label: "your answer",
      blindguess_guess_label: "now guess their answer",
      blindguess_yours: "yours",
      blindguess_you_guessed: "you guessed",
      blindguess_you_guessed_them: "you guessed for",
      blindguess_guessed_for_you: "guessed for you",
      blindguess_actual: "actual",
      blindguess_guessed: "guessed",
      blindguess_read_score: "read them right",
      blindguess_you_read_them: "you read them",
      blindguess_they_read_you: "they read you",
      // Badges
      badge_trending: "Trending",
      badge_viral: "Viral",
      badge_hot: "Hot",
      badge_new: "New",
      badge_popular: "Popular",
      "badge_new-badge": "New",
      // Marquee
      marquee_trending: "Trending now",
      marquee_plays: "50k+ rounds played",
      marquee_new: "3 new packs",
      marquee_dare: "dare to be honest?",
      marquee_viral: "Going viral",
      marquee_send: "send it to your person",
      // Invite
      invite_title: "share with your person",
      invite_desc:
        "they'll get the same questions. no one sees answers until you both finish.",
      invite_copy: "copy",
      invite_simulate: "simulate: partner joins →",
      // Quiz
      quiz_back: "back",
      quiz_next: "next",
      quiz_submit: "submit",
      quiz_question: "question",
      bubble_hint: "tap all that apply",
      swipe_hint: "pick all that fit",
      eliminate_hint: "tap to eliminate \u2014 last one wins",
      // Waiting
      waiting_title: "you're locked in 🔒",
      waiting_desc:
        'waiting for <strong style="color:var(--text)">Alex</strong> to finish answering...',
      waiting_progress: "Alex is on question 3 of 5",
      waiting_nudge: "👉 send a nudge",
      waiting_simulate: "simulate: partner done →",
      // Modal
      modal_title: "lock in your answers?",
      modal_desc:
        "once you submit, no take-backs. your person will be notified you're done.",
      modal_confirm: "lock it in",
      modal_cancel: "wait, go back",
      // Settings
      settings_mode: "Mode",
      settings_accent: "Accent Color",
      // Results
      results_matches: "matches",
      results_plot_twists: "plot twists",
      results_sync_rate: "sync rate",
      results_share: "📤 share this vibe check",
      results_play_another: "play another pack",
      results_back_home: "back home",
      results_you: "you",
      results_of: "of",
      // Reveal
      reveal_question_of: "question {n} of {total}",
      reveal_you: "You",
      reveal_tap_reveal: "tap to reveal",
      reveal_tap_continue: "tap to continue →",
      reveal_get_ready: "get ready",
      // Feedback
      feedback_copied: "copied!",
      feedback_nudge_sent: "✅ nudge sent!",
      feedback_link_copied: "✅ link copied!",
      // Delete
      delete_title: "remove this session?",
      delete_desc:
        "this will remove the session from your list. this can't be undone.",
      delete_confirm: "remove",
      delete_cancel: "cancel",
      delete_label: "Delete",
      // Auth
      auth_pick_username: "pick a username",
      auth_pick_subtitle: "just a name so your partner knows it's you",
      auth_continue: "continue",
      auth_welcome_back: "welcome back",
      auth_sign_in: "sign in",
      auth_back: "back",
      auth_create_account_title: "create your account",
      auth_create_account: "create account",
      auth_signing_in: "signing in as {name}",
      auth_nice_to_meet: "nice to meet you, {name}",
      auth_enter_password: "enter your password",
      auth_password_min_chars: "password must be at least 4 characters",
      auth_passwords_no_match: "passwords don't match",
      auth_password_placeholder: "your password...",
      auth_create_password_placeholder: "create a password...",
      auth_confirm_password_placeholder: "confirm password...",
      // Waiting (dynamic)
      waiting_default_desc: "waiting for your partner to finish answering...",
      waiting_checking: "checking...",
      waiting_share_code: "share this code with your partner:",
      waiting_copy_link: "copy link",
      waiting_for_partner_named: "waiting for {name} to finish answering...",
      waiting_for_partner_join:
        "waiting for your partner to join and answer...",
      waiting_both_done: "both done!",
      waiting_partner_done: "partner is done! waiting for you...",
      waiting_answering: "{name} is answering...",
      waiting_partner: "partner",
      waiting_submit_error:
        "Could not submit answers. Check your connection and try again.",
      // Save account
      save_title: "keep your account?",
      save_desc:
        "set a password so you can come back, see your history, and start new sessions anytime.",
      save_confirm: "save account",
      save_skip: "skip for now",
      // Nav
      nav_profile: "You",
      // Profile
      profile_sessions: "sessions",
      profile_completed: "completed",
      profile_packs_tried: "packs tried",
      profile_settings: "settings",
      profile_account: "account",
      profile_theme: "theme & colors",
      profile_language: "language",
      profile_save_account: "save account",
      profile_logout: "log out",
      profile_plan_active: "active",
      profile_plan_label: "plan",
      profile_next_billing: "next billing",
      profile_payment: "payment",
      profile_manage: "manage subscription",
      profile_manage_info: "subscription management will be available soon",
      profile_cancel: "cancel plan",
      profile_cancel_confirm: "are you sure you want to cancel blindside+?",
      profile_feat_packs: "all packs",
      profile_feat_insights: "deep insights",
      profile_feat_advisor: "AI advisor",
      // Settings
      settings_dark: "🌙 Dark",
      settings_light: "☀️ Light",
      // Invite
      invite_start: "start answering →",
      // Results loading
      results_loading: "loading results...",
      results_load_error: "could not load results",
      results_see_answers: "see all answers",
      // Vibe labels
      vibe_0_title: "Wildly Different",
      vibe_0_desc: "opposites attract...right?",
      vibe_0_intro:
        "Well, this was... <strong>eventful</strong>. You two see the world through very different lenses — and honestly, that might be the most interesting part.",
      vibe_20_title: "Unpredictable Duo",
      vibe_20_desc: "never a boring moment",
      vibe_20_intro:
        "You two are <strong>unpredictable</strong> in the best way. Not always on the same page, but always an interesting read.",
      vibe_40_title: "Getting There",
      vibe_40_desc: "common ground exists",
      vibe_40_intro:
        "There's real <strong>overlap</strong> here — and where there isn't, there's curiosity. That counts for a lot.",
      vibe_60_title: "Real Ones",
      vibe_60_desc: "you get each other",
      vibe_60_intro:
        "You two <strong>get each other</strong>. Not perfectly, not always — but more than most. And the differences? That's where the good conversations live.",
      vibe_80_title: "Mind Readers",
      vibe_80_desc: "basically the same person",
      vibe_80_intro:
        "OK this is getting <strong>suspicious</strong>. You two are answering like you share a brain. Who copied who?",
      vibe_100_title: "Literally Telepathic",
      vibe_100_desc: "this is actually scary",
      vibe_100_intro:
        "<strong>Every. Single. One.</strong> You matched on all of them. This is either beautiful or terrifying. Probably both.",
      // Premium
      premium_title: "unlock blindside+",
      premium_subtitle: "go deeper with your person",
      premium_price: "$4.99",
      premium_period: "/month",
      premium_was_price: "$9.99",
      premium_cta: "start free trial",
      premium_restore: "restore purchase",
      premium_feature_packs: "all 30+ question packs",
      premium_feature_insights: "deep relationship insights",
      premium_feature_advisor: "AI relationship advisor",
      premium_feature_unlimited: "unlimited sessions",
      premium_social_proof: "12,400+ couples upgraded this month",
      premium_lock_label: "pro",
      premium_banner_text: "this pack is part of blindside+",
      premium_limited: "limited time — 50% off",
      premium_guarantee: "loved by 94% of couples who tried it",
      premium_trial_note: "cancel anytime — no charge during trial",
      // Insights & Advisor
      insights_title: "deep insights",
      insights_unlock: "unlock deep insights with blindside+",
      insights_coming_soon:
        "full insights launching soon — you'll be first to know",
      insight_communication: "communication style match",
      insight_compatibility: "emotional compatibility score",
      insight_growth: "relationship growth areas",
      insight_tension: "hidden tension points",
      insight_self_awareness: "self-awareness score",
      insight_hidden_patterns: "hidden behavior patterns",
      insight_next_steps: "personalized next steps",
      insight_strengths: "your core strengths",
      advisor_title: "AI advisor",
      advisor_unlock: "get personalized advice with blindside+",
      advisor_coming_soon: "AI advisor launching soon — stay tuned",
      advisor_teaser_msg:
        "based on your answers, i noticed something interesting about how you two communicate...",
      advisor_prompt_1: "how can we communicate better?",
      advisor_prompt_2: "what should we talk about tonight?",
      advisor_prompt_3: "where do we differ most?",
      advisor_prompt_solo_1: "what does this say about me?",
      advisor_prompt_solo_2: "how can i grow from this?",
      advisor_prompt_solo_3: "what patterns should i watch?",
      insights_page_title: "insights & advisor",
      insights_card_desc: "deep analysis of your relationships",
      insights_val_strong: "strong",
      insights_val_building: "building",
      insights_val_areas: "areas",
      insights_val_low: "low",
      insights_val_unknown: "not enough data",
      insights_desc_communication:
        "how well you and your partner express and understand each other",
      insights_desc_compatibility:
        "your overall emotional alignment across sessions",
      insights_desc_growth: "topics and areas you've explored together",
      insights_desc_tension:
        "potential friction points based on differing answers",
      insights_stat_sessions: "sessions",
      insights_stat_partners: "partners",
      insights_stat_topics: "topics",
      insights_play_more: "play more sessions to unlock deeper insights",
      results_view_insights: "view insights & advisor",
      // Stranger matching
      stranger_meet: "meet a stranger",
      stranger_tagline: "same questions. blind answers. see if you vibe.",
      stranger_find: "find a match",
      stranger_subtitle: "you'll play a random pack with someone new",
      stranger_looking: "looking for someone...",
      stranger_cancel: "cancel",
      stranger_found: "found someone!",
      stranger_playing: "playing",
      stranger_expired: "no one around right now",
      stranger_try_again: "try again",
      stranger_vote_title: "vibe with {name}?",
      stranger_vote_yes: "yes, chat",
      stranger_vote_no: "nah, next",
      stranger_match: "it's a match!",
      stranger_match_desc: "you both said yes",
      stranger_no_match: "maybe next time",
      stranger_no_match_desc: "it wasn't mutual this time",
      stranger_play_again: "find someone new",
      stranger_waiting_vote: "waiting for their answer...",
      stranger_back: "back home",
      // Landing page
      land_nav_play: "play now",
      land_hero_title: "Get to know each other<br>by playing games",
      land_hero_sub:
        "Same questions. Neither sees the other's answers. Results revealed together. Takes 3 minutes.",
      land_hero_cta: "create a session",
      land_hero_note: "free. no account needed.",
      land_hero_proof: "<span>2,400+</span> sessions played",
      land_profile_badge: "Your Blindside Profile",
      land_profile_title: "Just play.<br>Your profile builds itself.",
      land_profile_sub:
        "Every game you play — with a date, a friend, anyone — adds to your profile. No forms. No effort. Just answers.",
      land_profile_f1_title: "Complete decks",
      land_profile_f1_desc:
        "Play different packs to unlock new layers of your profile across topics.",
      land_profile_f2_title: "Play with anyone",
      land_profile_f2_desc:
        "Partners, friends, crushes, celebrities. Each session sharpens your data.",
      land_profile_f3_title: "See your real patterns",
      land_profile_f3_desc:
        "Over time, Blindside maps how you actually think, connect, and compare — across everyone you've played with.",
      land_profile_cta: "Start building yours",
      land_random_badge: "Live matching",
      land_random_title: "Don't know anyone?<br>Play with a stranger.",
      land_random_sub:
        "Get matched with someone random. Same questions, blind answers. See if you vibe — no names, no pressure.",
      land_random_step1: "Join queue",
      land_random_step2: "Answer blind",
      land_random_step3: "See if you match",
      land_random_cta: "Find a stranger",
      land_random_note: "anonymous · takes 3 minutes · free",
      land_how_label: "how it works",
      land_how_step1: "Answer 10 questions. <span>Honestly.</span>",
      land_how_step2: "Send the link. <span>They answer too.</span>",
      land_how_step3: "Both see everything. <span>At the same time.</span>",
      land_moment:
        "You matched on an app. You met at a party. You've been talking for a week but still have no idea what they actually think. <strong>Now you do.</strong>",
      land_examples_label: "example questions",
      land_q1: "Right now you want:",
      land_q1_o1: "something serious",
      land_q1_o2: "something fun with potential",
      land_q1_o3: "honestly no idea",
      land_q1_o4: "none of your business",
      land_q2: "The party ends at midnight. You leave at:",
      land_q2_o1: "11:45",
      land_q2_o2: "midnight exactly",
      land_q2_o3: "2am",
      land_q2_o4: "helping clean up at 3am",
      land_q3: "When someone doesn't text back for 12 hours:",
      land_q3_o1: "already moved on mentally",
      land_q3_o2: "fine, not checking",
      land_q3_o3: "three unsent messages",
      land_q3_o4: "already told your friends",
      land_when_label: "when to play",
      land_when1:
        "After a party when you have their Instagram but <em>don't know if there's anything there.</em>",
      land_when2:
        "Before a first date when you want a signal <em>without committing to the whole thing.</em>",
      land_when3: "With a friend you've <em>always been curious about.</em>",
      land_when4:
        "When you just want to know <em>if it's worth getting dressed for.</em>",
      land_stat_sessions: "sessions played",
      land_stat_packs: "question packs",
      land_stat_time: "average session",
      land_quote1: '"we learned more in 3 minutes than in 3 weeks of texting"',
      land_quote1_author: "couple matched on hinge",
      land_quote2: '"sent it to my situationship at 11pm. we\'re dating now."',
      land_quote2_author: "@maya, 23",
      land_quote3:
        '"the reveal part is genuinely nerve-wracking in the best way"',
      land_quote3_author: "played with best friend",
      land_waitlist_title: "get early access.",
      land_waitlist_sub: "be first when sessions go live.",
      land_waitlist_btn: "i'm in",
      land_waitlist_success: "you're in ✓",
      land_footer_sub:
        "built for the moment right after you meet someone interesting.",
    },

    tr: {
      splash_tagline: "aynı sorular. gizli cevaplar. bir açılış.",
      splash_get_started: "başla",
      splash_have_account: "hesabım var",
      guest_invited: "davetlisiniz! 🎉",
      guest_title: "oyuna katıl",
      guest_subtitle: "oynamaya başlamak için bir isim girin",
      guest_placeholder: "adınız...",
      guest_play: "misafir olarak oyna",
      guest_have_account: "hesabım var",
      guest_error_min_chars: "en az 2 karakter",
      guest_error_connection: "bağlantı hatası, tekrar deneyin",
      onboarding_title: "nasıl çalışır",
      onboarding_step1_title: "bir paket seç",
      onboarding_step1_desc: "tarzına uyan bir soru paketi seç",
      onboarding_step2_title: "gizlice cevapla",
      onboarding_step2_desc:
        "ikiniz de aynı soruları cevaplıyorsunuz — gözetleme yok",
      onboarding_step3_title: "birlikte aç",
      onboarding_step3_desc:
        "cevaplar ancak ikiniz de gönderdikten sonra açılır",
      onboarding_cta: "hadi başlayalım",
      home_all: "Tümü",
      home_active: "Aktif",
      home_completed: "Tamamlanan",
      home_invite_sent: "davet gönderildi",
      home_new_session: "+ yeni oturum",
      home_loading: "yükleniyor...",
      home_no_sessions: "henüz oturum yok — bir tane başlat!",
      home_with: "ile",
      home_waiting_partner: "partner bekleniyor",
      home_done: "tamamlandı",
      home_load_error: "oturumlar yüklenemedi",
      home_show_more: "Daha fazla göster",
      home_with_alex: "Alex ile",
      home_with_jordan: "Jordan ile",
      home_with_taylor_match: "Taylor ile · %83 eşleşme",
      badge_reveal: "Aç!",
      badge_progress: "Devam ediyor",
      badge_waiting: "Bekliyor",
      pack_couples: "Çiftler Paketi",
      pack_bestfriends: "En İyi Arkadaşlar",
      pack_deeptalk: "Derin Sohbet",
      pack_36questions: "Aşık Olmak İçin 36 Soru",
      pack_friendship_deep_dive: "Arkadaşlık Analizi",
      pack_count_couples: "10 soru",
      pack_count_bestfriends: "10 soru",
      pack_count_deeptalk: "10 soru",
      pack_count_36questions: "36 soru · Arthur Aron'un çalışmasına dayanır",
      pack_hottakes: "Keskin Yorumlar",
      pack_redflags: "Red Flag mı Değil mi",
      pack_chaotic: "Kaotik Enerji",
      pack_strangervibes: "Yabancı Vibes",
      pack_count_hottakes: "10 soru · sadece cesur fikirler",
      pack_count_redflags: "10 soru · yargıla rahatça",
      pack_count_chaotic: "10 soru · çılgın vibes",
      pack_count_strangervibes: "15 soru · internet bağımlısı enerjisi",
      pack_desc_strangervibes:
        "meme'ler, kaos & sıfır filtre. anlayan yabancılar için.",
      pack_drunkconfessions: "Sarhoş İtirafları",
      pack_count_drunkconfessions: "15 soru · sıvı cesaret edisyonu",
      pack_desc_drunkconfessions:
        "birkaç kadehten sonra söyleyeceğin şeyler. filtre yok, pişmanlık yok.",
      pack_fungames: "Eğlence & Oyunlar",
      pack_worldtaste: "Dünya & Lezzetler",
      pack_cinematastes: "Sinema Zevkleri",
      pack_cinemascenes: "İkonik Sahneler",
      pack_cinemadebates: "Sinema Tartışmaları",
      pack_ethics: "Etik & İkilemler",
      pack_situations: "Durumlar",
      pack_cuisine: "Mutfak Uyumu",
      pack_livingtogether: "Birlikte Yaşam",
      pack_soulspirit: "Ruh & Mana",
      pack_count_fungames: "10 soru · hafif eğlence",
      pack_count_worldtaste: "10 soru · kültür & tatlar",
      pack_count_cinematastes:
        "12 soru · türler, atıştırmalıklar & suçluluk filmleri",
      pack_count_cinemascenes: "12 soru · ikonik anlar & karakterler",
      pack_count_cinemadebates: "12 soru · sinema tartışmaları",
      pack_count_ethics: "10 soru · ahlaki kavşaklar",
      pack_count_situations: "10 soru · hayata tepki ver",
      pack_count_cuisine: "15 soru · yemek & lezzet uyumu",
      pack_count_livingtogether: "10 soru · ev arkadaşlığı",
      pack_count_soulspirit: "10 soru · anlam & inanç",
      pack_desc_fungames: "hafif kaos. yanlış cevap yok.",
      pack_desc_worldtaste:
        "seyahat, yemek, kültür — ne kadar dünya vatandaşısın?",
      pack_desc_cinematastes:
        "türler, yönetmenler, suçluluk filmleri — gerçekten aynı şeyleri mi izliyorsunuz?",
      pack_desc_cinemascenes:
        "kötü karakterler, senaryo dönüşleri, film ölümleri — sizi şekillendiren anları yeniden yaşayın",
      pack_desc_cinemadebates:
        "altyazı mı dublaj mı, devam filmleri, spoiler — sinema tartışmalarını bir kez sonlandırın",
      pack_desc_cuisine:
        "acı seviyesi, favori karbonhidrat, yemek kırmızı çizgileri — gerçekten uyumlu musunuz?",
      pack_desc_situations:
        "gerçek hayat anları. gerçekten nasıl tepki verirdin?",
      nav_home: "Ana Sayfa",
      nav_packs: "Paketler",
      packs_subtitle: "birini seç, gönder, neler olacak gör",
      packs_trending: "şu an trend",
      packs_all: "tüm paketler",
      packs_played: "oynandı",
      pack_desc_36questions:
        "yabancıları aşık eden viral çalışma. cesaret eder misin?",
      pack_desc_hottakes: "sadece keskin fikirler. çit üstü yok.",
      pack_desc_redflags: "birbirinizi yargılayın. merhamet yok.",
      cat_all: "Tümü",
      cat_love: "Aşk",
      cat_friends: "Arkadaş",
      cat_spicy: "Ateşli",
      cat_deep: "Derin",
      cat_culture: "Kültür",
      cat_lifestyle: "Yaşam",
      cat_self: "Kendin",
      packs_collections: "koleksiyonlar",
      coll_decks: "deste",
      coll_date_night: "Randevu Gecesi",
      coll_desc_date_night: "derinleşmek isteyen çiftler için mükemmel paket",
      coll_spicy_edition: "Acı Versiyon",
      coll_desc_spicy_edition: "hot take, red flag & kaos — hepsi bir arada",
      coll_deep_bonds: "Derin Bağlar",
      coll_desc_deep_bonds: "gerçekten önemli olan anlamlı sohbetler",
      coll_friend_zone: "Arkadaş Bölgesi",
      coll_desc_friend_zone:
        "sen ve en yakın arkadaşın için eğlence & gerçek konuşma",
      coll_culture_taste: "Kültür & Zevk",
      coll_desc_culture_taste:
        "seyahat, inançlar & yaşam tarzı — ne kadar uyumlusunuz?",
      coll_cinema_night: "Sinema Gecesi",
      coll_desc_cinema_night:
        "türler, ikonik sahneler & keskin yorumlar — film ruh eşi misiniz?",
      coll_know_your_partner: "Partnerini Tanı",
      coll_desc_know_your_partner:
        "partneriniz hakkında çözüp paylaşacağınız arketip testleri",
      coll_know_yourself: "Kendini Tanı",
      coll_desc_know_yourself: "kişilik, gölge, sınırlar — tam bir iç keşif",
      coll_love_decoded: "Aşk Çözümlendi",
      coll_desc_love_decoded: "bağlanma, aşk dili & ilişki kalıpların",
      coll_relationship_xray: "İlişki Röntgeni",
      coll_desc_relationship_xray:
        "dinamikleri gör — çift hikayesi, gizli gerçekler & daha fazlası",
      coll_inner_work: "İç Çalışma",
      coll_desc_inner_work: "stres, sabotaj & gölge — iyileştiren zor şeyler",
      pack_attachment: "Bağlanma Stili",
      pack_innermirror: "İç Ayna",
      pack_stresstype: "Stres Tepkisi",
      pack_count_attachment: "10 soru · nasıl seviyorsun",
      pack_count_innermirror: "10 soru · gerçekte kim olduğun",
      pack_count_stresstype: "10 soru · savaş, kaç, don veya uy",
      pack_desc_attachment: "bağlanma stilini keşfet. partner gerekmiyor.",
      pack_desc_innermirror: "kişiliğine bir ayna. sadece sen.",
      solo_badge: "Solo",
      solo_your_result: "sonucun",
      solo_dominant_trait: "baskın özellik",
      solo_breakdown: "tam analiz",
      solo_take_another: "başka test yap",
      solo_you_probably: "muhtemelen sen...",
      solo_note_to_self: "kendine not",
      mode_partner: "Partner",
      mode_self: "Kendin",
      pack_lovelang: "Sevgi Dili",
      pack_shadow: "Gölge Ben",
      pack_emotionalage: "Duygusal Yaş",
      pack_boundaries: "Sınır Kontrolü",
      pack_selfsabotage: "Kendini Sabote",
      pack_count_lovelang: "10 soru · nasıl seviyorsun",
      pack_count_shadow: "10 soru · kendinden sakladıkların",
      pack_count_emotionalage: "10 soru · iç dünyanın yaşı",
      pack_count_boundaries: "10 soru · duvarlar, filtreler, açık kapılar",
      pack_count_selfsabotage: "10 soru · neden kendi önüne geçiyorsun",
      pack_desc_lovelang:
        "5 sevgi diline dayalı. uyarı: duygulara neden olabilir.",
      pack_desc_emotionalage: "yaşın değil — duygusal yaşın. nadiren aynıdır.",
      pack_zodiacenergy: "Burç Enerjisi",
      pack_moonphase: "Ay Evresi",
      pack_cosmiclove: "Kozmik Aşk Stili",
      pack_count_zodiacenergy: "10 soru · ateş, toprak, hava, su",
      pack_count_moonphase: "10 soru · hangi ay evresindesin",
      pack_count_cosmiclove:
        "10 soru · gezegenler aşkını nasıl şekillendiriyor",
      pack_desc_zodiacenergy:
        "damarlarında hangi element akıyor? doğum haritası gerekmiyor.",
      pack_desc_moonphase:
        "kişiliğin bir ay evresi olarak. uyarı: ürkütücü derecede doğru.",
      pack_desc_cosmiclove:
        "venüs, mars, ay, jüpiter — kalbini hangi gezegen yönetiyor?",
      coll_cosmic_self: "Kozmik Ben",
      coll_desc_cosmic_self: "burç, ay evreleri & gezegen aşkı — kozmik planın",
      pack_partnertype: "Partner Arketipi",
      pack_partnerera: "Partner Dönemi",
      pack_couplestory: "Çift Hikayesi",
      pack_whattheyhide: "Sakladıkları",
      pack_count_partnertype: "10 soru · partnerin hangi tip?",
      pack_count_partnerera: "10 soru · hangi dönemdesin?",
      pack_count_couplestory: "10 soru · çift dinamiğiniz",
      pack_count_whattheyhide: "10 soru · söylenmeyen gerçekler",
      pack_desc_partnertype:
        "golden retriever mı kaos ajanı mı? arketipini keşfet.",
      pack_desc_partnerera:
        "ana karakter, şifacı, ölümüne sadık, yoksa yumuşak kötü?",
      pack_desc_couplestory:
        "ruh eşleri, macera ikilisi, kaos çifti, yoksa yavaş yanan aşk?",
      pack_desc_whattheyhide: "hissedip hiç söylemedikleri şeyler.",
      pack_loyalty: "Sadakat Testi",
      pack_count_loyalty: "10 soru · güven mi kopuş mu",
      pack_desc_loyalty:
        "gerçekten ne kadar sadıksın? senaryolar, yeşil bayraklar ve gerçek.",
      pack_flirtguess: "Flört & Tahmin",
      pack_desirematch: "Arzu Eşleşmesi",
      pack_count_flirtguess: "10 soru · cevapla + tahmin et",
      pack_count_desirematch: "10 soru · cevapla + tahmin et",
      pack_desc_flirtguess:
        "dürüstçe cevapla. sonra onun ne dediğini tahmin et.",
      pack_desc_desirematch:
        "senin istediğin vs onun istediği. gerçekten ne kadar tanıyorsun?",
      coll_blind_guess: "Kör Tahmin",
      coll_desc_blind_guess:
        "kendin cevapla, sonra partnerini tahmin et. çift açılış.",
      blindguess_own_label: "senin cevabın",
      blindguess_guess_label: "şimdi onun cevabını tahmin et",
      blindguess_yours: "senin",
      blindguess_you_guessed: "tahmin ettin",
      blindguess_you_guessed_them: "tahminin",
      blindguess_guessed_for_you: "senin için tahmin etti",
      blindguess_actual: "gerçek",
      blindguess_guessed: "tahmin etti",
      blindguess_read_score: "doğru okudu",
      blindguess_you_read_them: "sen onu okudun",
      blindguess_they_read_you: "o seni okudu",
      badge_trending: "Trend",
      badge_viral: "Viral",
      badge_hot: "Popüler",
      badge_new: "Yeni",
      badge_popular: "Sevilen",
      "badge_new-badge": "Yeni",
      marquee_trending: "Şu an trend",
      marquee_plays: "50k+ tur oynandı",
      marquee_new: "3 yeni paket",
      marquee_dare: "dürüst olmaya cesaretin var mı?",
      marquee_viral: "Viral oluyor",
      marquee_send: "kişine gönder",
      invite_title: "kişinle paylaş",
      invite_desc:
        "aynı soruları alacak. ikiniz de bitirene kadar kimse cevapları göremez.",
      invite_copy: "kopyala",
      invite_simulate: "simülasyon: partner katılıyor →",
      quiz_back: "geri",
      quiz_next: "ileri",
      quiz_submit: "gönder",
      quiz_question: "soru",
      bubble_hint: "uygun olanların hepsine dokun",
      swipe_hint: "uyanların hepsini seç",
      eliminate_hint: "elemek için dokun \u2014 son kalan kazanır",
      waiting_title: "kilitlendin 🔒",
      waiting_desc:
        '<strong style="color:var(--text)">Alex</strong>\'in cevaplaması bekleniyor...',
      waiting_progress: "Alex 5 sorudan 3. soruda",
      waiting_nudge: "👉 dürt",
      waiting_simulate: "simülasyon: partner bitti →",
      modal_title: "cevaplarını kilitle?",
      modal_desc: "gönderdikten sonra geri dönüş yok. kişine bildirim gidecek.",
      modal_confirm: "kilitle",
      modal_cancel: "dur, geri dön",
      settings_mode: "Mod",
      settings_accent: "Vurgu Rengi",
      results_matches: "eşleşme",
      results_plot_twists: "sürpriz",
      results_sync_rate: "uyum oranı",
      results_share: "📤 vibe check'i paylaş",
      results_play_another: "başka paket oyna",
      results_back_home: "ana sayfaya dön",
      results_you: "sen",
      results_of: "/",
      reveal_question_of: "soru {n} / {total}",
      reveal_you: "Sen",
      reveal_tap_reveal: "açmak için dokun",
      reveal_tap_continue: "devam için dokun →",
      reveal_get_ready: "hazır ol",
      feedback_copied: "kopyalandı!",
      feedback_nudge_sent: "✅ dürtü gönderildi!",
      feedback_link_copied: "✅ link kopyalandı!",
      delete_title: "bu oturumu kaldır?",
      delete_desc: "bu oturumu listenden kaldıracak. bu işlem geri alınamaz.",
      delete_confirm: "kaldır",
      delete_cancel: "iptal",
      delete_label: "Sil",
      auth_pick_username: "kullanıcı adı seç",
      auth_pick_subtitle: "partnerinin seni tanıması için bir isim yeter",
      auth_continue: "devam",
      auth_welcome_back: "tekrar hoş geldin",
      auth_sign_in: "giriş yap",
      auth_back: "geri",
      auth_create_account_title: "hesabını oluştur",
      auth_create_account: "hesap oluştur",
      auth_signing_in: "{name} olarak giriş yapılıyor",
      auth_nice_to_meet: "tanıştığımıza memnunum, {name}",
      auth_enter_password: "şifreni gir",
      auth_password_min_chars: "şifre en az 4 karakter olmalı",
      auth_passwords_no_match: "şifreler eşleşmiyor",
      auth_password_placeholder: "şifren...",
      auth_create_password_placeholder: "şifre oluştur...",
      auth_confirm_password_placeholder: "şifreyi onayla...",
      waiting_default_desc: "partnerinin cevaplarını bitirmesi bekleniyor...",
      waiting_checking: "kontrol ediliyor...",
      waiting_share_code: "bu kodu partnerinle paylaş:",
      waiting_copy_link: "linki kopyala",
      waiting_for_partner_named:
        "{name} cevaplarını bitirsin diye bekleniyor...",
      waiting_for_partner_join:
        "partnerinin katılması ve cevap vermesi bekleniyor...",
      waiting_both_done: "ikisi de bitti!",
      waiting_partner_done: "partner bitti! seni bekliyor...",
      waiting_answering: "{name} cevaplıyor...",
      waiting_partner: "partner",
      waiting_submit_error:
        "Cevaplar gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.",
      save_title: "hesabını sakla?",
      save_desc:
        "geri dönebilmek, geçmişini görebilmek ve yeni oturumlar başlatabilmek için bir şifre belirle.",
      save_confirm: "hesabı kaydet",
      save_skip: "şimdilik geç",
      nav_profile: "Sen",
      profile_sessions: "oturum",
      profile_completed: "tamamlandı",
      profile_packs_tried: "denenen paket",
      profile_settings: "ayarlar",
      profile_account: "hesap",
      profile_theme: "tema ve renkler",
      profile_language: "dil",
      profile_save_account: "hesabı kaydet",
      profile_logout: "çıkış yap",
      profile_plan_active: "aktif",
      profile_plan_label: "plan",
      profile_next_billing: "sonraki fatura",
      profile_payment: "ödeme",
      profile_manage: "aboneliği yönet",
      profile_manage_info: "abonelik yönetimi yakında kullanılabilir olacak",
      profile_cancel: "planı iptal et",
      profile_cancel_confirm:
        "blindside+ iptal etmek istediğinize emin misiniz?",
      profile_feat_packs: "tüm paketler",
      profile_feat_insights: "derin analizler",
      profile_feat_advisor: "AI danışman",
      settings_dark: "🌙 Koyu",
      settings_light: "☀️ Açık",
      invite_start: "cevaplamaya başla →",
      results_loading: "sonuçlar yükleniyor...",
      results_load_error: "sonuçlar yüklenemedi",
      results_see_answers: "tüm cevapları gör",
      vibe_0_title: "Bambaşka",
      vibe_0_desc: "zıtlar birbirini çeker...değil mi?",
      vibe_0_intro:
        "Şey, bu... <strong>hareketliydi</strong>. İkiniz dünyaya çok farklı açılardan bakıyorsunuz — ve açıkçası, en ilginç kısmı bu olabilir.",
      vibe_20_title: "Tahmin Edilemez İkili",
      vibe_20_desc: "asla sıkıcı bir an yok",
      vibe_20_intro:
        "İkiniz en iyi şekilde <strong>öngörülemezsiniz</strong>. Her zaman aynı sayfada değilsiniz ama her zaman ilginç bir okuma.",
      vibe_40_title: "Yolda",
      vibe_40_desc: "ortak nokta var",
      vibe_40_intro:
        "Burada gerçek bir <strong>örtüşme</strong> var — ve olmayan yerde merak var. Bu çok şey ifade ediyor.",
      vibe_60_title: "Gerçek Olanlar",
      vibe_60_desc: "birbirinizi anlıyorsunuz",
      vibe_60_intro:
        "İkiniz <strong>birbirinizi anlıyorsunuz</strong>. Mükemmel değil, her zaman değil — ama çoğundan fazla. Farklar mı? İyi sohbetlerin yaşandığı yer orası.",
      vibe_80_title: "Zihin Okuyucular",
      vibe_80_desc: "aynı kişi gibisiniz",
      vibe_80_intro:
        "Tamam bu <strong>şüpheli</strong> olmaya başladı. İkiniz aynı beyni paylaşıyormuşsunuz gibi cevaplıyorsunuz. Kim kimden kopya çekti?",
      vibe_100_title: "Tam Telepati",
      vibe_100_desc: "bu gerçekten korkutucu",
      vibe_100_intro:
        "<strong>Her. Bir. Tanesi.</strong> Hepsinde eşleştiniz. Bu ya güzel ya da korkutucu. Muhtemelen ikisi de.",
      // Premium
      premium_title: "blindside+ aç",
      premium_subtitle: "ilişkinizi derinleştirin",
      premium_price: "$4.99",
      premium_period: "/ay",
      premium_was_price: "$9.99",
      premium_cta: "ücretsiz denemeyi başlat",
      premium_restore: "satın almayı geri yükle",
      premium_feature_packs: "tüm 30+ soru paketi",
      premium_feature_insights: "derin ilişki analizleri",
      premium_feature_advisor: "AI ilişki danışmanı",
      premium_feature_unlimited: "sınırsız oturum",
      premium_social_proof: "bu ay 12.400+ çift yükseltti",
      premium_lock_label: "pro",
      premium_banner_text: "bu paket blindside+ kapsamında",
      premium_limited: "sınırlı süre — %50 indirim",
      premium_guarantee: "deneyen çiftlerin %94'ü tarafından sevildi",
      premium_trial_note:
        "istediğin zaman iptal et — deneme süresince ücret yok",
      insights_title: "derin analizler",
      insights_unlock: "blindside+ ile derin analizlerin kilidini aç",
      insights_coming_soon: "tam analizler yakında — ilk sen öğreneceksin",
      insight_communication: "iletişim tarzı uyumu",
      insight_compatibility: "duygusal uyumluluk puanı",
      insight_growth: "ilişki gelişim alanları",
      insight_tension: "gizli gerilim noktaları",
      insight_self_awareness: "öz farkındalık puanı",
      insight_hidden_patterns: "gizli davranış kalıpları",
      insight_next_steps: "kişiselleştirilmiş sonraki adımlar",
      insight_strengths: "temel güçlü yönlerin",
      advisor_title: "AI danışman",
      advisor_unlock: "blindside+ ile kişisel tavsiye al",
      advisor_coming_soon: "AI danışman yakında — takipte kal",
      advisor_teaser_msg:
        "cevaplarınıza dayanarak, ikinizin iletişim şekli hakkında ilginç bir şey fark ettim...",
      advisor_prompt_1: "nasıl daha iyi iletişim kurabiliriz?",
      advisor_prompt_2: "bu gece ne hakkında konuşmalıyız?",
      advisor_prompt_3: "en çok nerede farklıyız?",
      advisor_prompt_solo_1: "bu benim hakkımda ne söylüyor?",
      advisor_prompt_solo_2: "bundan nasıl gelişebilirim?",
      advisor_prompt_solo_3: "hangi kalıplara dikkat etmeliyim?",
      insights_page_title: "analizler ve danışman",
      insights_card_desc: "ilişkilerinizin derin analizi",
      insights_val_strong: "güçlü",
      insights_val_building: "gelişiyor",
      insights_val_areas: "alan",
      insights_val_low: "düşük",
      insights_val_unknown: "yeterli veri yok",
      insights_desc_communication:
        "siz ve partneriniz ne kadar iyi ifade ediyor ve anlıyorsunuz",
      insights_desc_compatibility:
        "oturumlar arasındaki genel duygusal uyumunuz",
      insights_desc_growth: "birlikte keşfettiğiniz konular ve alanlar",
      insights_desc_tension:
        "farklı cevaplara dayanan potansiyel sürtüşme noktaları",
      insights_stat_sessions: "oturum",
      insights_stat_partners: "partner",
      insights_stat_topics: "konu",
      insights_play_more: "daha derin analizler için daha fazla oturum oynayın",
      results_view_insights: "analizleri ve danışmanı gör",
      // Stranger matching
      stranger_meet: "yabancıyla tanış",
      stranger_tagline: "aynı sorular. gizli cevaplar. uyumunuzu görün.",
      stranger_find: "eşleşme bul",
      stranger_subtitle: "yeni biriyle rastgele bir paket oynayacaksınız",
      stranger_looking: "birisi aranıyor...",
      stranger_cancel: "iptal",
      stranger_found: "birisi bulundu!",
      stranger_playing: "oynanıyor",
      stranger_expired: "şu an kimse yok",
      stranger_try_again: "tekrar dene",
      stranger_vote_title: "{name} ile vibin var mı?",
      stranger_vote_yes: "evet, sohbet",
      stranger_vote_no: "yok, sonraki",
      stranger_match: "eşleşme!",
      stranger_match_desc: "ikiniz de evet dediniz",
      stranger_no_match: "belki bir dahaki sefere",
      stranger_no_match_desc: "bu sefer karşılıklı olmadı",
      stranger_play_again: "yeni birini bul",
      stranger_waiting_vote: "cevapları bekleniyor...",
      stranger_back: "ana sayfaya dön",
      // Landing page
      land_nav_play: "hemen oyna",
      land_hero_title: "Oyun oynayarak<br>birbirinizi tanıyın",
      land_hero_sub:
        "Aynı sorular. Kimse diğerinin cevaplarını görmez. Sonuçlar birlikte açılır. 3 dakika sürer.",
      land_hero_cta: "oturum oluştur",
      land_hero_note: "ücretsiz. hesap gerekmez.",
      land_hero_proof: "<span>2,400+</span> oturum oynandı",
      land_profile_badge: "Blindside Profili",
      land_profile_title: "Sadece oyna.<br>Profil kendini oluştursun.",
      land_profile_sub:
        "Oynadığın her oyun — bir buluşma, bir arkadaş, herkes — profiline eklenir. Form yok. Çaba yok. Sadece cevaplar.",
      land_profile_f1_title: "Desteleri tamamla",
      land_profile_f1_desc:
        "Farklı paketler oynayarak profilinde yeni katmanlar aç.",
      land_profile_f2_title: "Herkesle oyna",
      land_profile_f2_desc:
        "Partnerler, arkadaşlar, hoşlandıkların. Her oturum verini keskinleştirir.",
      land_profile_f3_title: "Gerçek kalıplarını gör",
      land_profile_f3_desc:
        "Zamanla Blindside, nasıl düşündüğünü, bağ kurduğunu ve karşılaştırdığını haritalandırır.",
      land_profile_cta: "Profilini oluşturmaya başla",
      land_random_badge: "Canlı eşleşme",
      land_random_title: "Kimseyi tanımıyor musun?<br>Bir yabancıyla oyna.",
      land_random_sub:
        "Rastgele biriyle eşleş. Aynı sorular, gizli cevaplar. Vibin var mı bak — isim yok, baskı yok.",
      land_random_step1: "Sıraya gir",
      land_random_step2: "Gizlice cevapla",
      land_random_step3: "Eşleşiyor musun bak",
      land_random_cta: "Bir yabancı bul",
      land_random_note: "anonim · 3 dakika sürer · ücretsiz",
      land_how_label: "nasıl çalışır",
      land_how_step1: "10 soruyu cevapla. <span>Dürüstçe.</span>",
      land_how_step2: "Linki gönder. <span>Onlar da cevaplar.</span>",
      land_how_step3: "İkiniz de her şeyi görür. <span>Aynı anda.</span>",
      land_moment:
        "Bir uygulamada eşleştiniz. Bir partide tanıştınız. Bir haftadır konuşuyorsunuz ama gerçekte ne düşündüklerini hâlâ bilmiyorsunuz. <strong>Artık biliyorsunuz.</strong>",
      land_examples_label: "örnek sorular",
      land_q1: "Şu an ne istiyorsun:",
      land_q1_o1: "ciddi bir şey",
      land_q1_o2: "potansiyelli eğlenceli bir şey",
      land_q1_o3: "dürüst olmak gerekirse hiçbir fikrim yok",
      land_q1_o4: "seni ilgilendirmez",
      land_q2: "Parti gece yarısı bitiyor. Sen saat kaçta gidiyorsun:",
      land_q2_o1: "23:45",
      land_q2_o2: "tam gece yarısı",
      land_q2_o3: "sabah 2",
      land_q2_o4: "sabah 3'te temizliğe yardım ediyorum",
      land_q3: "Biri 12 saat mesaj atmayınca:",
      land_q3_o1: "çoktan unutmuşum",
      land_q3_o2: "sorun yok, bakmıyorum",
      land_q3_o3: "üç tane gönderilmemiş mesaj",
      land_q3_o4: "arkadaşlarıma çoktan anlattım",
      land_when_label: "ne zaman oynanır",
      land_when1:
        "Bir partiden sonra Instagram'ını aldın ama <em>bir şey var mı bilmiyorsun.</em>",
      land_when2:
        "İlk buluşmadan önce bir sinyal istiyorsun <em>ama tüm sürece girmeden.</em>",
      land_when3: "Hep <em>merak ettiğin</em> bir arkadaşınla.",
      land_when4: "Sadece <em>giyinmeye değer mi</em> bilmek istiyorsun.",
      land_stat_sessions: "oturum oynandı",
      land_stat_packs: "soru paketi",
      land_stat_time: "ortalama oturum",
      land_quote1: '"3 dakikada 3 haftalık mesajlaşmadan fazlasını öğrendik"',
      land_quote1_author: "hinge'de eşleşen çift",
      land_quote2:
        "\"gece 11'de situationship'ime gönderdim. artık çıkıyoruz.\"",
      land_quote2_author: "@maya, 23",
      land_quote3: '"açılma kısmı gerçekten harika bir şekilde geriyor"',
      land_quote3_author: "en yakın arkadaşıyla oynadı",
      land_waitlist_title: "erken erişim al.",
      land_waitlist_sub: "oturumlar açıldığında ilk sen ol.",
      land_waitlist_btn: "beni yaz",
      land_waitlist_success: "tamam, listedesin ✓",
      land_footer_sub: "ilginç biriyle tanıştıktan hemen sonrası için yapıldı.",
    },

    th: {
      splash_tagline: "คำถามเดียวกัน คำตอบลับ เปิดเผยพร้อมกัน",
      splash_get_started: "เริ่มเลย",
      splash_have_account: "ฉันมีบัญชีแล้ว",
      guest_invited: "คุณได้รับเชิญ! 🎉",
      guest_title: "เข้าร่วมเกม",
      guest_subtitle: "ใส่ชื่อเพื่อเริ่มเล่น",
      guest_placeholder: "ชื่อของคุณ...",
      guest_play: "เล่นในฐานะแขก",
      guest_have_account: "ฉันมีบัญชีแล้ว",
      guest_error_min_chars: "อย่างน้อย 2 ตัวอักษร",
      guest_error_connection: "เชื่อมต่อผิดพลาด ลองอีกครั้ง",
      onboarding_title: "วิธีใช้งาน",
      onboarding_step1_title: "เลือกชุดคำถาม",
      onboarding_step1_desc: "เลือกชุดคำถามที่เข้ากับคุณ",
      onboarding_step2_title: "ตอบแบบส่วนตัว",
      onboarding_step2_desc: "ทั้งคู่ตอบคำถามเดียวกัน — ห้ามแอบดู",
      onboarding_step3_title: "เปิดเผยด้วยกัน",
      onboarding_step3_desc: "คำตอบจะเปิดเผยเมื่อทั้งสองคนส่งแล้วเท่านั้น",
      onboarding_cta: "เริ่มเลย",
      home_all: "ทั้งหมด",
      home_active: "กำลังดำเนินการ",
      home_completed: "เสร็จสิ้น",
      home_invite_sent: "ส่งคำเชิญแล้ว",
      home_new_session: "+ เซสชันใหม่",
      home_loading: "กำลังโหลด...",
      home_no_sessions: "ยังไม่มีเซสชัน — เริ่มเลย!",
      home_with: "กับ",
      home_waiting_partner: "รอคู่หู",
      home_done: "เสร็จแล้ว",
      home_load_error: "ไม่สามารถโหลดเซสชันได้",
      home_show_more: "แสดงเพิ่มเติม",
      home_with_alex: "กับ Alex",
      home_with_jordan: "กับ Jordan",
      home_with_taylor_match: "กับ Taylor · ตรงกัน 83%",
      badge_reveal: "เปิดเผย!",
      badge_progress: "กำลังทำ",
      badge_waiting: "รอ",
      pack_couples: "คู่รัก",
      pack_bestfriends: "เพื่อนซี้",
      pack_deeptalk: "คุยลึก",
      pack_36questions: "36 คำถามเพื่อตกหลุมรัก",
      pack_friendship_deep_dive: "เจาะลึกมิตรภาพ",
      pack_count_couples: "10 คำถาม",
      pack_count_bestfriends: "10 คำถาม",
      pack_count_deeptalk: "10 คำถาม",
      pack_count_36questions: "36 คำถาม · อ้างอิงจากงานวิจัยของ Arthur Aron",
      pack_hottakes: "ความเห็นแรง",
      pack_redflags: "Red Flag หรือเปล่า",
      pack_chaotic: "พลังวุ่นวาย",
      pack_strangervibes: "ไวบ์คนแปลกหน้า",
      pack_count_hottakes: "10 คำถาม · ความเห็นแบบจัดจ้าน",
      pack_count_redflags: "10 คำถาม · ตัดสินได้เลย",
      pack_count_chaotic: "10 คำถาม · ไวบ์บ้าบอ",
      pack_count_strangervibes: "15 คำถาม · พลังติดจอ",
      pack_desc_strangervibes:
        "มีม ความวุ่นวาย & ไม่มีฟิลเตอร์ สำหรับคนแปลกหน้าที่เข้าใจ",
      pack_drunkconfessions: "สารภาพตอนเมา",
      pack_count_drunkconfessions: "15 คำถาม · ฉบับกล้าเพราะเมา",
      pack_desc_drunkconfessions:
        "สิ่งที่จะพูดได้หลังดื่มไปสักแก้ว ไม่มีฟิลเตอร์ ไม่มีเสียใจ",
      pack_fungames: "สนุก & เกม",
      pack_worldtaste: "โลก & รสชาติ",
      pack_cinematastes: "รสนิยมหนัง",
      pack_cinemascenes: "ฉากสุดคลาสสิก",
      pack_cinemadebates: "ดีเบตหนัง",
      pack_ethics: "จริยธรรม & ทางเลือก",
      pack_situations: "สถานการณ์",
      pack_cuisine: "จับคู่รสชาติ",
      pack_livingtogether: "อยู่ด้วยกัน",
      pack_soulspirit: "จิตวิญญาณ",
      pack_count_fungames: "10 คำถาม · สนุกเบาๆ",
      pack_count_worldtaste: "10 คำถาม · วัฒนธรรม & รสชาติ",
      pack_count_cinematastes: "12 คำถาม · แนวหนัง ขนม & guilty pleasure",
      pack_count_cinemascenes: "12 คำถาม · ช่วงเวลาสุดคลาสสิก & ตัวละคร",
      pack_count_cinemadebates: "12 คำถาม · ความเห็นแรงเรื่องหนัง",
      pack_count_ethics: "10 คำถาม · ทางแยกศีลธรรม",
      pack_count_situations: "10 คำถาม · ตอบสนองต่อชีวิต",
      pack_count_cuisine: "15 คำถาม · อาหาร & รสชาติ",
      pack_count_livingtogether: "10 คำถาม · ชีวิตร่วมกัน",
      pack_count_soulspirit: "10 คำถาม · ความหมาย & ความเชื่อ",
      pack_desc_fungames: "ความวุ่นวายเบาๆ ไม่มีคำตอบผิด",
      pack_desc_worldtaste: "ท่องเที่ยว อาหาร วัฒนธรรม — คุณรู้จักโลกแค่ไหน?",
      pack_desc_cinematastes:
        "แนวหนัง ผู้กำกับ guilty pleasure — ดูเรื่องเดียวกันจริงไหม?",
      pack_desc_cinemascenes:
        "ตัวร้าย พล็อตทวิสต์ ตายในหนัง — ฉากที่หล่อหลอมคุณ",
      pack_desc_cinemadebates:
        "ซับ vs พากย์ ภาคต่อ สปอยล์ — ยุติดีเบตหนังให้จบ",
      pack_desc_cuisine:
        "ระดับเผ็ด คาร์บโปรด เรื่องอาหารที่รับไม่ได้ — เข้ากันจริงไหม?",
      pack_desc_situations: "ช่วงเวลาในชีวิตจริง คุณจะตอบสนองยังไง?",
      nav_home: "หน้าแรก",
      nav_packs: "ชุดคำถาม",
      packs_subtitle: "เลือกชุด ส่งไป แล้วดูผลลัพธ์",
      packs_trending: "กำลังฮิต",
      packs_all: "ชุดทั้งหมด",
      packs_played: "เล่นแล้ว",
      pack_desc_36questions:
        "งานวิจัยไวรัลที่ทำให้คนแปลกหน้าตกหลุมรัก กล้าไหม?",
      pack_desc_hottakes: "ความเห็นแบบจัดจ้านเท่านั้น ห้ามอยู่กลางๆ",
      pack_desc_redflags: "ตัดสินกันเลย ไม่ต้องเกรงใจ",
      cat_all: "ทั้งหมด",
      cat_love: "รัก",
      cat_friends: "เพื่อน",
      cat_spicy: "แซ่บ",
      cat_deep: "ลึก",
      cat_culture: "วัฒนธรรม",
      cat_lifestyle: "ไลฟ์สไตล์",
      cat_self: "ตัวเอง",
      packs_collections: "คอลเลกชัน",
      coll_decks: "สำรับ",
      coll_date_night: "คืนเดท",
      coll_desc_date_night: "แพ็กสมบูรณ์แบบสำหรับคู่รักที่อยากรู้จักกันลึกขึ้น",
      coll_spicy_edition: "เผ็ดร้อน",
      coll_desc_spicy_edition:
        "ความเห็นแรง ธงแดง & ความวุ่นวาย — ครบในแพ็กเดียว",
      coll_deep_bonds: "สายสัมพันธ์ลึก",
      coll_desc_deep_bonds: "บทสนทนาที่มีความหมายจริงๆ",
      coll_friend_zone: "โซนเพื่อน",
      coll_desc_friend_zone: "สนุก & คุยจริงจังกับเพื่อนซี้",
      coll_culture_taste: "วัฒนธรรม & รสนิยม",
      coll_desc_culture_taste: "เที่ยว ความเชื่อ & ไลฟ์สไตล์ — เข้ากันแค่ไหน?",
      coll_cinema_night: "คืนดูหนัง",
      coll_desc_cinema_night:
        "แนวหนัง ฉากสุดคลาสสิก & ความเห็นแรง — เป็นคู่หนังกันจริงไหม?",
      coll_know_your_partner: "รู้จักคนรัก",
      coll_desc_know_your_partner:
        "แบบทดสอบอาร์คีไทป์เกี่ยวกับคนรักของคุณ & แชร์ผล",
      coll_know_yourself: "รู้จักตัวเอง",
      coll_desc_know_yourself:
        "บุคลิกภาพ เงามืด ขอบเขต — ดำดิ่งสู่ภายในอย่างเต็มที่",
      coll_love_decoded: "ถอดรหัสความรัก",
      coll_desc_love_decoded: "ความผูกพัน ภาษารัก & รูปแบบความสัมพันธ์ของคุณ",
      coll_relationship_xray: "เอ็กซ์เรย์ความสัมพันธ์",
      coll_desc_relationship_xray:
        "มองทะลุพลวัต — เรื่องราวคู่ ความจริงที่ซ่อน & อีกมากมาย",
      coll_inner_work: "งานภายใน",
      coll_desc_inner_work:
        "ความเครียด การทำลายตัวเอง & เงามืด — สิ่งยากที่เยียวยา",
      pack_attachment: "สไตล์ความผูกพัน",
      pack_innermirror: "กระจกภายใน",
      pack_stresstype: "การตอบสนองต่อความเครียด",
      pack_count_attachment: "10 คำถาม · คุณรักแบบไหน",
      pack_count_innermirror: "10 คำถาม · ตัวตนที่แท้จริง",
      pack_count_stresstype: "10 คำถาม · สู้ หนี แข็ง หรือตาม",
      pack_desc_attachment: "ค้นพบสไตล์ความผูกพัน ไม่ต้องมีคู่",
      pack_desc_innermirror: "กระจกส่องบุคลิกภาพ แค่คุณ",
      solo_badge: "เดี่ยว",
      solo_your_result: "ผลลัพธ์ของคุณ",
      solo_dominant_trait: "ลักษณะเด่น",
      solo_breakdown: "วิเคราะห์ทั้งหมด",
      solo_take_another: "ทำแบบทดสอบอื่น",
      solo_you_probably: "คุณอาจจะ...",
      solo_note_to_self: "โน้ตถึงตัวเอง",
      mode_partner: "คู่หู",
      mode_self: "ตัวเอง",
      pack_lovelang: "ภาษารัก",
      pack_shadow: "ตัวตนที่ซ่อน",
      pack_emotionalage: "อายุทางอารมณ์",
      pack_boundaries: "เช็คขอบเขต",
      pack_selfsabotage: "ทำลายตัวเอง",
      pack_count_lovelang: "10 คำถาม · คุณให้และรับความรักยังไง",
      pack_count_shadow: "10 คำถาม · สิ่งที่ซ่อนจากตัวเอง",
      pack_count_emotionalage: "10 คำถาม · ตัวตนข้างในอายุเท่าไหร่",
      pack_count_boundaries: "10 คำถาม · กำแพง ฟิลเตอร์ หรือประตูเปิด",
      pack_count_selfsabotage: "10 คำถาม · ทำไมถึงขวางตัวเอง",
      pack_desc_lovelang: "อิงจาก 5 ภาษารัก เตือน: อาจทำให้เกิดความรู้สึก",
      pack_desc_emotionalage: "ไม่ใช่อายุคุณ — อายุทางอารมณ์ แทบไม่เคยเท่ากัน",
      pack_zodiacenergy: "พลังจักรราศี",
      pack_moonphase: "เฟสดวงจันทร์",
      pack_cosmiclove: "สไตล์รักจักรวาล",
      pack_count_zodiacenergy: "10 คำถาม · ไฟ ดิน ลม น้ำ",
      pack_count_moonphase: "10 คำถาม · คุณเป็นเฟสดวงจันทร์ไหน",
      pack_count_cosmiclove: "10 คำถาม · ดาวเคราะห์กำหนดความรักยังไง",
      pack_desc_zodiacenergy: "ธาตุไหนไหลในสายเลือด? ไม่ต้องใช้ดวงชะตา",
      pack_desc_moonphase: "บุคลิกภาพเป็นเฟสดวงจันทร์ เตือน: แม่นจนน่ากลัว",
      pack_desc_cosmiclove:
        "วีนัส มาร์ส ดวงจันทร์ จูปิเตอร์ — ดาวไหนครองหัวใจ?",
      coll_cosmic_self: "ตัวตนจักรวาล",
      coll_desc_cosmic_self:
        "จักรราศี เฟสดวงจันทร์ & รักดาวเคราะห์ — พิมพ์เขียวจักรวาลของคุณ",
      pack_partnertype: "อาร์คีไทป์คนรัก",
      pack_partnerera: "ยุคคนรัก",
      pack_couplestory: "เรื่องราวคู่รัก",
      pack_whattheyhide: "สิ่งที่เขาซ่อน",
      pack_count_partnertype: "10 คำถาม · คนรักเป็นแบบไหน?",
      pack_count_partnerera: "10 คำถาม · คุณอยู่ในยุคไหน?",
      pack_count_couplestory: "10 คำถาม · ไดนามิกของคู่คุณ",
      pack_count_whattheyhide: "10 คำถาม · ความจริงที่ไม่เคยพูด",
      pack_desc_partnertype:
        "โกลเด้นรีทรีฟเวอร์หรือตัวแทนแห่งความวุ่นวาย? ค้นหาอาร์คีไทป์คนรัก",
      pack_desc_partnerera:
        "ตัวละครหลัก, ผู้เยียวยา, ตายด้วยกัน, หรือวายร้ายอ่อนโยน?",
      pack_desc_couplestory:
        "เนื้อคู่, คู่ผจญภัย, คู่วุ่นวาย, หรือรักค่อยเป็นค่อยไป?",
      pack_desc_whattheyhide: "สิ่งที่เขารู้สึกแต่ไม่เคยพูดออกมา",
      pack_loyalty: "ทดสอบความซื่อสัตย์",
      pack_count_loyalty: "10 คำถาม · ไว้ใจหรือไม่ไว้ใจ",
      pack_desc_loyalty:
        "ซื่อสัตย์แค่ไหนกัน? สถานการณ์จริง สัญญาณดี และความจริง",
      pack_flirtguess: "จีบ & ทาย",
      pack_desirematch: "จับคู่ความปรารถนา",
      pack_count_flirtguess: "10 คำถาม · ตอบ + ทาย",
      pack_count_desirematch: "10 คำถาม · ตอบ + ทาย",
      pack_desc_flirtguess: "ตอบตามจริง แล้วทายว่าเขาตอบอะไร กล้าไหม?",
      pack_desc_desirematch:
        "สิ่งที่คุณต้องการ vs สิ่งที่เขาต้องการ รู้จักกันดีแค่ไหน?",
      coll_blind_guess: "ทายสุ่ม",
      coll_desc_blind_guess: "ตอบเอง แล้วทายคนรัก เปิดเผยสองเท่า",
      blindguess_own_label: "คำตอบของคุณ",
      blindguess_guess_label: "ทายคำตอบของเขา",
      blindguess_yours: "ของคุณ",
      blindguess_you_guessed: "คุณทาย",
      blindguess_you_guessed_them: "คุณทายให้",
      blindguess_guessed_for_you: "ทายให้คุณ",
      blindguess_actual: "จริงๆ",
      blindguess_guessed: "ทาย",
      blindguess_read_score: "อ่านถูก",
      blindguess_you_read_them: "คุณอ่านเขา",
      blindguess_they_read_you: "เขาอ่านคุณ",
      badge_trending: "ฮิต",
      badge_viral: "ไวรัล",
      badge_hot: "ฮอต",
      badge_new: "ใหม่",
      badge_popular: "ยอดนิยม",
      "badge_new-badge": "ใหม่",
      marquee_trending: "กำลังฮิต",
      marquee_plays: "50k+ รอบที่เล่น",
      marquee_new: "3 ชุดใหม่",
      marquee_dare: "กล้าพูดตรงไหม?",
      marquee_viral: "กำลังไวรัล",
      marquee_send: "ส่งให้คนของคุณ",
      invite_title: "แชร์ให้คนของคุณ",
      invite_desc:
        "พวกเขาจะได้คำถามเดียวกัน ไม่มีใครเห็นคำตอบจนกว่าทั้งคู่จะตอบเสร็จ",
      invite_copy: "คัดลอก",
      invite_simulate: "จำลอง: คู่หูเข้าร่วม →",
      quiz_back: "กลับ",
      quiz_next: "ถัดไป",
      quiz_submit: "ส่ง",
      quiz_question: "คำถาม",
      bubble_hint: "แตะทุกข้อที่ตรง",
      swipe_hint: "เลือกทุกข้อที่ใช่",
      eliminate_hint: "แตะเพื่อตัดออก \u2014 ตัวสุดท้ายชนะ",
      waiting_title: "คุณพร้อมแล้ว 🔒",
      waiting_desc: 'รอ <strong style="color:var(--text)">Alex</strong>...',
      waiting_progress: "Alex ตอบถึงข้อ 3 จาก 5",
      waiting_nudge: "👉 เตือน",
      waiting_simulate: "จำลอง: คู่หูตอบเสร็จ →",
      modal_title: "ยืนยันคำตอบ?",
      modal_desc: "เมื่อส่งแล้วจะแก้ไม่ได้ คู่หูของคุณจะได้รับแจ้ง",
      modal_confirm: "ยืนยัน",
      modal_cancel: "เดี๋ยวก่อน กลับไป",
      settings_mode: "โหมด",
      settings_accent: "สีเน้น",
      results_matches: "ตรงกัน",
      results_plot_twists: "เซอร์ไพรส์",
      results_sync_rate: "อัตราซิงค์",
      results_share: "📤 แชร์ไวบ์เช็ค",
      results_play_another: "เล่นชุดอื่น",
      results_back_home: "กลับหน้าแรก",
      results_you: "คุณ",
      results_of: "จาก",
      reveal_question_of: "คำถาม {n} จาก {total}",
      reveal_you: "คุณ",
      reveal_tap_reveal: "แตะเพื่อเปิดเผย",
      reveal_tap_continue: "แตะเพื่อไปต่อ →",
      reveal_get_ready: "เตรียมตัว",
      feedback_copied: "คัดลอกแล้ว!",
      feedback_nudge_sent: "✅ เตือนแล้ว!",
      feedback_link_copied: "✅ คัดลอกลิงก์แล้ว!",
      delete_title: "ลบเซสชันนี้?",
      delete_desc: "เซสชันจะถูกลบออกจากรายการของคุณ ไม่สามารถย้อนกลับได้",
      delete_confirm: "ลบ",
      delete_cancel: "ยกเลิก",
      delete_label: "ลบ",
      auth_pick_username: "เลือกชื่อผู้ใช้",
      auth_pick_subtitle: "แค่ชื่อเพื่อให้คู่ของคุณรู้ว่าเป็นคุณ",
      auth_continue: "ดำเนินการต่อ",
      auth_welcome_back: "ยินดีต้อนรับกลับ",
      auth_sign_in: "เข้าสู่ระบบ",
      auth_back: "กลับ",
      auth_create_account_title: "สร้างบัญชีของคุณ",
      auth_create_account: "สร้างบัญชี",
      auth_signing_in: "กำลังเข้าสู่ระบบเป็น {name}",
      auth_nice_to_meet: "ยินดีที่ได้รู้จัก, {name}",
      auth_enter_password: "ใส่รหัสผ่านของคุณ",
      auth_password_min_chars: "รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร",
      auth_passwords_no_match: "รหัสผ่านไม่ตรงกัน",
      auth_password_placeholder: "รหัสผ่านของคุณ...",
      auth_create_password_placeholder: "สร้างรหัสผ่าน...",
      auth_confirm_password_placeholder: "ยืนยันรหัสผ่าน...",
      waiting_default_desc: "รอให้คู่ของคุณตอบคำถามเสร็จ...",
      waiting_checking: "กำลังตรวจสอบ...",
      waiting_share_code: "แชร์โค้ดนี้กับคู่ของคุณ:",
      waiting_copy_link: "คัดลอกลิงก์",
      waiting_for_partner_named: "รอให้ {name} ตอบคำถามเสร็จ...",
      waiting_for_partner_join: "รอให้คู่ของคุณเข้าร่วมและตอบ...",
      waiting_both_done: "ทั้งคู่เสร็จแล้ว!",
      waiting_partner_done: "คู่ของคุณเสร็จแล้ว! รอคุณอยู่...",
      waiting_answering: "{name} กำลังตอบ...",
      waiting_partner: "คู่หู",
      waiting_submit_error:
        "ไม่สามารถส่งคำตอบได้ ตรวจสอบการเชื่อมต่อและลองอีกครั้ง",
      save_title: "เก็บบัญชีไว้?",
      save_desc:
        "ตั้งรหัสผ่านเพื่อกลับมาดูประวัติและเริ่มเซสชันใหม่ได้ทุกเมื่อ",
      save_confirm: "บันทึกบัญชี",
      save_skip: "ข้ามไปก่อน",
      nav_profile: "คุณ",
      profile_sessions: "เซสชัน",
      profile_completed: "เสร็จแล้ว",
      profile_packs_tried: "แพ็คที่ลอง",
      profile_settings: "การตั้งค่า",
      profile_account: "บัญชี",
      profile_theme: "ธีมและสี",
      profile_language: "ภาษา",
      profile_save_account: "บันทึกบัญชี",
      profile_logout: "ออกจากระบบ",
      profile_plan_active: "ใช้งานอยู่",
      profile_plan_label: "แผน",
      profile_next_billing: "เรียกเก็บเงินครั้งถัดไป",
      profile_payment: "การชำระเงิน",
      profile_manage: "จัดการการสมัคร",
      profile_manage_info: "การจัดการการสมัครจะพร้อมใช้งานเร็วๆ นี้",
      profile_cancel: "ยกเลิกแผน",
      profile_cancel_confirm: "คุณแน่ใจหรือว่าต้องการยกเลิก blindside+?",
      profile_feat_packs: "ทุกแพ็ค",
      profile_feat_insights: "วิเคราะห์เชิงลึก",
      profile_feat_advisor: "ที่ปรึกษา AI",
      settings_dark: "🌙 มืด",
      settings_light: "☀️ สว่าง",
      invite_start: "เริ่มตอบ →",
      results_loading: "กำลังโหลดผลลัพธ์...",
      results_load_error: "ไม่สามารถโหลดผลลัพธ์ได้",
      results_see_answers: "ดูคำตอบทั้งหมด",
      vibe_0_title: "แตกต่างสุดขั้ว",
      vibe_0_desc: "ขั้วตรงข้ามดึงดูดกัน...ใช่ไหม?",
      vibe_0_intro:
        "อืม นี่มัน... <strong>มีสีสัน</strong> คุณสองคนมองโลกผ่านเลนส์ที่ต่างกันมาก — แต่บอกตรงๆ นั่นอาจเป็นส่วนที่น่าสนใจที่สุด",
      vibe_20_title: "คู่คาดเดาไม่ได้",
      vibe_20_desc: "ไม่มีช่วงเวลาน่าเบื่อ",
      vibe_20_intro:
        "คุณสองคน<strong>คาดเดาไม่ได้</strong>ในทางที่ดีที่สุด ไม่ได้อยู่หน้าเดียวกันเสมอ แต่น่าอ่านเสมอ",
      vibe_40_title: "กำลังไปได้ดี",
      vibe_40_desc: "มีจุดร่วม",
      vibe_40_intro:
        "มี<strong>จุดร่วม</strong>จริงๆ ตรงนี้ — และตรงที่ไม่มี ก็มีความอยากรู้ นั่นมีค่ามาก",
      vibe_60_title: "ตัวจริง",
      vibe_60_desc: "เข้าใจกัน",
      vibe_60_intro:
        "คุณสองคน<strong>เข้าใจกัน</strong> ไม่สมบูรณ์แบบ ไม่ใช่ทุกครั้ง — แต่มากกว่าคนส่วนใหญ่ ส่วนที่ต่าง? ตรงนั้นแหละที่บทสนทนาดีๆ เกิดขึ้น",
      vibe_80_title: "อ่านใจได้",
      vibe_80_desc: "เหมือนคนเดียวกัน",
      vibe_80_intro:
        "โอเค นี่เริ่ม<strong>น่าสงสัย</strong>แล้ว คุณสองคนตอบเหมือนใช้สมองเดียวกัน ใครลอกใคร?",
      vibe_100_title: "เทเลพาธีแท้",
      vibe_100_desc: "น่ากลัวจริงๆ",
      vibe_100_intro:
        "<strong>ทุก. คำถาม. เลย.</strong> ตรงกันหมด นี่มันสวยงามหรือน่ากลัว อาจจะทั้งสองอย่าง",
      // Premium
      premium_title: "ปลดล็อก blindside+",
      premium_subtitle: "ลึกซึ้งยิ่งขึ้นกับคนของคุณ",
      premium_price: "$4.99",
      premium_period: "/เดือน",
      premium_was_price: "$9.99",
      premium_cta: "เริ่มทดลองฟรี",
      premium_restore: "กู้คืนการซื้อ",
      premium_feature_packs: "แพ็คคำถามทั้งหมด 30+",
      premium_feature_insights: "วิเคราะห์ความสัมพันธ์เชิงลึก",
      premium_feature_advisor: "ที่ปรึกษาความสัมพันธ์ AI",
      premium_feature_unlimited: "เซสชันไม่จำกัด",
      premium_social_proof: "12,400+ คู่อัปเกรดเดือนนี้",
      premium_lock_label: "pro",
      premium_banner_text: "แพ็คนี้อยู่ใน blindside+",
      premium_limited: "เวลาจำกัด — ลด 50%",
      premium_guarantee: "94% ของคู่รักที่ลองแล้วชอบ",
      premium_trial_note: "ยกเลิกได้ตลอดเวลา — ไม่เสียค่าใช้จ่ายระหว่างทดลอง",
      insights_title: "วิเคราะห์เชิงลึก",
      insights_unlock: "ปลดล็อกการวิเคราะห์เชิงลึกกับ blindside+",
      insights_coming_soon: "การวิเคราะห์เต็มรูปแบบเปิดตัวเร็วๆ นี้",
      insight_communication: "ความเข้ากันของสไตล์การสื่อสาร",
      insight_compatibility: "คะแนนความเข้ากันทางอารมณ์",
      insight_growth: "พื้นที่เติบโตของความสัมพันธ์",
      insight_tension: "จุดความตึงเครียดที่ซ่อนอยู่",
      insight_self_awareness: "คะแนนการตระหนักรู้ตนเอง",
      insight_hidden_patterns: "รูปแบบพฤติกรรมที่ซ่อนอยู่",
      insight_next_steps: "ขั้นตอนถัดไปส่วนบุคคล",
      insight_strengths: "จุดแข็งหลักของคุณ",
      advisor_title: "ที่ปรึกษา AI",
      advisor_unlock: "รับคำแนะนำส่วนตัวกับ blindside+",
      advisor_coming_soon: "ที่ปรึกษา AI เปิดตัวเร็วๆ นี้",
      advisor_teaser_msg:
        "จากคำตอบของคุณ ฉันสังเกตเห็นสิ่งที่น่าสนใจเกี่ยวกับวิธีการสื่อสารของคุณสองคน...",
      advisor_prompt_1: "เราสื่อสารกันดีขึ้นได้อย่างไร?",
      advisor_prompt_2: "คืนนี้ควรคุยเรื่องอะไร?",
      advisor_prompt_3: "เราต่างกันมากที่สุดตรงไหน?",
      advisor_prompt_solo_1: "สิ่งนี้บอกอะไรเกี่ยวกับฉัน?",
      advisor_prompt_solo_2: "ฉันเติบโตจากสิ่งนี้ได้อย่างไร?",
      advisor_prompt_solo_3: "ควรระวังรูปแบบอะไร?",
      insights_page_title: "วิเคราะห์และที่ปรึกษา",
      insights_card_desc: "การวิเคราะห์เชิงลึกของความสัมพันธ์",
      insights_val_strong: "แข็งแกร่ง",
      insights_val_building: "กำลังสร้าง",
      insights_val_areas: "ด้าน",
      insights_val_low: "ต่ำ",
      insights_val_unknown: "ข้อมูลไม่เพียงพอ",
      insights_desc_communication: "คุณและคู่ของคุณแสดงออกและเข้าใจกันดีแค่ไหน",
      insights_desc_compatibility: "ความสอดคล้องทางอารมณ์โดยรวมในทุกเซสชัน",
      insights_desc_growth: "หัวข้อและด้านที่คุณสำรวจร่วมกัน",
      insights_desc_tension: "จุดเสียดทานที่อาจเกิดขึ้นจากคำตอบที่แตกต่าง",
      insights_stat_sessions: "เซสชัน",
      insights_stat_partners: "คู่",
      insights_stat_topics: "หัวข้อ",
      insights_play_more: "เล่นเซสชันเพิ่มเพื่อปลดล็อกการวิเคราะห์ที่ลึกขึ้น",
      results_view_insights: "ดูการวิเคราะห์และที่ปรึกษา",
      // Stranger matching
      stranger_meet: "พบคนแปลกหน้า",
      stranger_tagline: "คำถามเดียวกัน คำตอบลับ ดูว่าคุณเข้ากันไหม",
      stranger_find: "หาคู่",
      stranger_subtitle: "คุณจะเล่นชุดสุ่มกับคนใหม่",
      stranger_looking: "กำลังหาใครสักคน...",
      stranger_cancel: "ยกเลิก",
      stranger_found: "เจอแล้ว!",
      stranger_playing: "กำลังเล่น",
      stranger_expired: "ไม่มีใครตอนนี้",
      stranger_try_again: "ลองอีกครั้ง",
      stranger_vote_title: "ไวบ์กับ {name} ไหม?",
      stranger_vote_yes: "ใช่ แชท",
      stranger_vote_no: "ไม่ ถัดไป",
      stranger_match: "แมทช์แล้ว!",
      stranger_match_desc: "คุณทั้งคู่ตอบใช่",
      stranger_no_match: "ไว้คราวหน้า",
      stranger_no_match_desc: "ครั้งนี้ยังไม่ตรงกัน",
      stranger_play_again: "หาคนใหม่",
      stranger_waiting_vote: "รอคำตอบของเขา...",
      stranger_back: "กลับหน้าแรก",
      // Landing page
      land_nav_play: "เล่นเลย",
      land_hero_title: "รู้จักกันมากขึ้น<br>ด้วยการเล่นเกม",
      land_hero_sub:
        "คำถามเดียวกัน ไม่มีใครเห็นคำตอบของอีกฝ่าย ผลลัพธ์เปิดเผยพร้อมกัน ใช้เวลา 3 นาที",
      land_hero_cta: "สร้างเซสชัน",
      land_hero_note: "ฟรี ไม่ต้องสมัครบัญชี",
      land_hero_proof: "<span>2,400+</span> เซสชันที่เล่นแล้ว",
      land_profile_badge: "โปรไฟล์ Blindside",
      land_profile_title: "แค่เล่น<br>โปรไฟล์สร้างเอง",
      land_profile_sub:
        "ทุกเกมที่คุณเล่น — กับเดท เพื่อน ใครก็ได้ — เพิ่มเข้าโปรไฟล์ ไม่ต้องกรอกฟอร์ม ไม่ต้องพยายาม แค่ตอบ",
      land_profile_f1_title: "เล่นให้ครบ",
      land_profile_f1_desc: "เล่นแพ็คต่างๆ เพื่อปลดล็อกโปรไฟล์ใหม่ๆ",
      land_profile_f2_title: "เล่นกับใครก็ได้",
      land_profile_f2_desc: "แฟน เพื่อน คนที่แอบชอบ ทุกเซสชันทำให้ข้อมูลคมขึ้น",
      land_profile_f3_title: "ดูรูปแบบจริงๆ",
      land_profile_f3_desc:
        "เมื่อเวลาผ่านไป Blindside จะแมปว่าคุณคิด เชื่อมต่อ และเปรียบเทียบยังไง",
      land_profile_cta: "เริ่มสร้างโปรไฟล์",
      land_random_badge: "จับคู่สด",
      land_random_title: "ไม่รู้จักใครเลย?<br>เล่นกับคนแปลกหน้า",
      land_random_sub:
        "จับคู่กับคนสุ่ม คำถามเดียวกัน คำตอบลับ ดูว่าเข้ากันไหม — ไม่มีชื่อ ไม่มีแรงกดดัน",
      land_random_step1: "เข้าคิว",
      land_random_step2: "ตอบแบบลับ",
      land_random_step3: "ดูว่าเข้ากันไหม",
      land_random_cta: "หาคนแปลกหน้า",
      land_random_note: "ไม่ระบุตัวตน · 3 นาที · ฟรี",
      land_how_label: "วิธีเล่น",
      land_how_step1: "ตอบ 10 คำถาม <span>อย่างซื่อสัตย์</span>",
      land_how_step2: "ส่งลิงก์ <span>เขาก็ตอบด้วย</span>",
      land_how_step3: "ทั้งคู่เห็นทุกอย่าง <span>พร้อมกัน</span>",
      land_moment:
        "คุณแมทช์กันในแอป คุณเจอกันที่ปาร์ตี้ คุยกันมาหนึ่งสัปดาห์แต่ยังไม่รู้ว่าเขาคิดอะไรจริงๆ <strong>ตอนนี้คุณรู้แล้ว</strong>",
      land_examples_label: "ตัวอย่างคำถาม",
      land_q1: "ตอนนี้คุณต้องการ:",
      land_q1_o1: "อะไรจริงจัง",
      land_q1_o2: "อะไรสนุกๆ ที่มีโอกาส",
      land_q1_o3: "ไม่รู้เลยจริงๆ",
      land_q1_o4: "ไม่ใช่เรื่องของคุณ",
      land_q2: "ปาร์ตี้จบตอนเที่ยงคืน คุณกลับตอน:",
      land_q2_o1: "23:45",
      land_q2_o2: "เที่ยงคืนพอดี",
      land_q2_o3: "ตี 2",
      land_q2_o4: "ช่วยเก็บตอนตี 3",
      land_q3: "เมื่อมีคนไม่ตอบแชท 12 ชั่วโมง:",
      land_q3_o1: "ลืมไปแล้ว",
      land_q3_o2: "โอเค ไม่ได้เช็ค",
      land_q3_o3: "ข้อความที่ยังไม่ได้ส่งสามอัน",
      land_q3_o4: "บอกเพื่อนไปแล้ว",
      land_when_label: "เล่นเมื่อไหร่",
      land_when1: "หลังปาร์ตี้ที่คุณได้ IG เขามาแต่<em>ไม่รู้ว่ามีอะไรไหม</em>",
      land_when2: "ก่อนเดทแรกที่อยากได้สัญญาณ<em>โดยไม่ต้องลงทุนทั้งหมด</em>",
      land_when3: "กับเพื่อนที่คุณ<em>อยากรู้มาตลอด</em>",
      land_when4: "เมื่อคุณแค่อยากรู้ว่า<em>คุ้มค่าที่จะแต่งตัวไปไหม</em>",
      land_stat_sessions: "เซสชันที่เล่น",
      land_stat_packs: "แพ็คคำถาม",
      land_stat_time: "เซสชันเฉลี่ย",
      land_quote1: '"เรียนรู้กันใน 3 นาทีมากกว่า 3 สัปดาห์ของการแชท"',
      land_quote1_author: "คู่ที่แมทช์กันใน hinge",
      land_quote2: '"ส่งให้คนที่คุยอยู่ตอน 5 ทุ่ม ตอนนี้คบกันแล้ว"',
      land_quote2_author: "@maya, 23",
      land_quote3: '"ตอนเปิดเผยคำตอบลุ้นมากในแบบที่ดี"',
      land_quote3_author: "เล่นกับเพื่อนสนิท",
      land_waitlist_title: "รับสิทธิ์ก่อนใคร",
      land_waitlist_sub: "เป็นคนแรกเมื่อเซสชันเปิดให้เล่น",
      land_waitlist_btn: "สนใจ",
      land_waitlist_success: "เรียบร้อย ✓",
      land_footer_sub: "สร้างมาสำหรับช่วงเวลาหลังจากที่คุณเจอคนที่น่าสนใจ",
    },
  },

  current:
    localStorage.getItem("bs-lang") ||
    (() => {
      const lang = (
        navigator.language ||
        navigator.userLanguage ||
        ""
      ).toLowerCase();
      if (lang.startsWith("tr")) return "tr";
      if (lang.startsWith("th")) return "th";
      return "en";
    })(),

  t(key) {
    return (
      this.translations[this.current]?.[key] || this.translations.en[key] || key
    );
  },

  setLanguage(lang) {
    if (!this.translations[lang]) return;
    this.current = lang;
    localStorage.setItem("bs-lang", lang);
    document.documentElement.setAttribute("lang", lang);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === "function") updateLangCycleBtn();
    // Re-render dynamic content
    if (typeof renderPacksGrid === "function") renderPacksGrid();
    if (typeof renderHomeSessions === "function" && currentScreen === "home")
      renderHomeSessions();
    if (typeof getQuestions === "function") {
      questions = getQuestions(selectedPackKey || "couples");
    }
  },

  applyAll() {
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      const val = this.t(key);
      if (el.innerHTML !== val) el.innerHTML = val;
    });
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
      const key = el.getAttribute("data-i18n-placeholder");
      el.placeholder = this.t(key);
    });
  },

  renderSelector() {
    const cur = this.languages[this.current];
    const options = Object.entries(this.languages)
      .filter(([code]) => code !== this.current)
      .map(
        ([code, { flag, label }]) =>
          `<button class="lang-dropdown-item" onclick="event.stopPropagation(); i18n.setLanguage('${code}')">
          <span class="lang-flag">${flag}</span>${label}
        </button>`,
      )
      .join("");
    const html = `
      <button class="lang-pill" onclick="event.stopPropagation(); this.parentElement.classList.toggle('open')">
        <span class="lang-flag">${cur.flag}</span>${cur.label}
      </button>
      <div class="lang-dropdown-menu">${options}</div>
    `;
    document.querySelectorAll(".lang-selector").forEach((el) => {
      el.innerHTML = html;
      el.classList.remove("open");
    });
  },

  init() {
    document.documentElement.setAttribute("lang", this.current);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === "function") updateLangCycleBtn();
    document.addEventListener("click", () => {
      document
        .querySelectorAll(".lang-selector.open")
        .forEach((el) => el.classList.remove("open"));
    });
  },
};

function cycleLang() {
  const codes = Object.keys(i18n.languages);
  const idx = codes.indexOf(i18n.current);
  const next = codes[(idx + 1) % codes.length];
  i18n.setLanguage(next);
}

function updateLangCycleBtn() {
  const flag = document.getElementById("langCycleFlag");
  if (flag) flag.textContent = i18n.languages[i18n.current]?.flag || "🌐";
}
