// ==================== i18n SYSTEM ====================
const i18n = {
  languages: {
    en: { flag: '🇬🇧', label: 'EN' },
    tr: { flag: '🇹🇷', label: 'TR' },
    th: { flag: '🇹🇭', label: 'TH' },
  },

  translations: {
    en: {
      // Splash
      splash_tagline: 'same questions. blind answers. one reveal.',
      splash_get_started: 'get started',
      splash_have_account: 'i have an account',
      // Guest Auth
      guest_invited: 'you\'ve been invited! 🎉',
      guest_title: 'join the game',
      guest_subtitle: 'enter a display name to start playing',
      guest_placeholder: 'your name...',
      guest_play: 'play as guest',
      guest_have_account: 'i have an account',
      guest_error_min_chars: 'at least 2 characters',
      guest_error_connection: 'connection error, try again',
      // Onboarding
      onboarding_title: 'how it works',
      onboarding_step1_title: 'pick a pack',
      onboarding_step1_desc: 'choose a question pack that matches your vibe',
      onboarding_step2_title: 'answer privately',
      onboarding_step2_desc: 'both of you answer the same questions — no peeking',
      onboarding_step3_title: 'reveal together',
      onboarding_step3_desc: 'answers unlock only when you\'ve both submitted',
      onboarding_cta: 'let\'s go',
      // Home
      home_all: 'All',
      home_active: 'Active',
      home_completed: 'Completed',
      home_invite_sent: 'invite sent',
      home_new_session: '+ new session',
      home_loading: 'loading...',
      home_no_sessions: 'no sessions yet — start one!',
      home_with: 'with',
      home_waiting_partner: 'waiting for partner',
      home_done: 'done',
      home_load_error: 'could not load sessions',
      home_show_more: 'Show more',
      home_with_alex: 'with Alex',
      home_with_jordan: 'with Jordan',
      home_with_taylor_match: 'with Taylor · 83% match',
      badge_reveal: 'Reveal!',
      badge_progress: 'In progress',
      badge_waiting: 'Waiting',
      // Pack names
      pack_couples: 'Couples Edition',
      pack_bestfriends: 'Best Friends',
      pack_deeptalk: 'Deep Talk',
      pack_coworkers: 'Coworkers',
      pack_36questions: '36 Questions to Fall in Love',
      pack_friendship_deep_dive: 'Friendship Deep Dive',
      // Pack counts
      pack_count_couples: '10 questions',
      pack_count_bestfriends: '10 questions',
      pack_count_deeptalk: '10 questions',
      pack_count_coworkers: '10 questions',
      pack_count_36questions: '36 questions · based on Arthur Aron\'s study',
      pack_hottakes: 'Hot Takes',
      pack_redflags: 'Red Flag or Nah',
      pack_chaotic: 'Chaotic Energy',
      pack_count_hottakes: '10 questions · spicy opinions only',
      pack_count_redflags: '10 questions · judge freely',
      pack_count_chaotic: '10 questions · unhinged vibes',
      pack_fungames: 'Fun & Games',
      pack_worldtaste: 'World & Taste',
      pack_ethics: 'Ethics & Dilemmas',
      pack_situations: 'Situations',
      pack_livingtogether: 'Living Together',
      pack_soulspirit: 'Soul & Spirit',
      pack_count_fungames: '10 questions · lighthearted fun',
      pack_count_worldtaste: '10 questions · culture & flavors',
      pack_count_ethics: '10 questions · moral crossroads',
      pack_count_situations: '10 questions · react to life',
      pack_count_livingtogether: '10 questions · cohabitation vibes',
      pack_count_soulspirit: '10 questions · meaning & belief',
      pack_desc_fungames: 'lighthearted chaos. no wrong answers.',
      pack_desc_worldtaste: 'travel, food, culture — how worldly are you?',
      pack_desc_situations: 'real-life moments. how would you actually react?',
      // Nav
      nav_home: 'Home',
      nav_packs: 'Decks',
      // Packs
      packs_subtitle: 'pick one, send it, see what happens',
      packs_trending: 'trending now',
      packs_all: 'all packs',
      packs_played: 'played',
      // Pack descriptions (featured cards)
      pack_desc_36questions: 'the viral study that makes strangers fall in love. are you brave enough?',
      pack_desc_hottakes: 'spicy opinions only. no fence-sitting allowed.',
      pack_desc_redflags: 'judge each other\'s takes. no mercy.',
      // Category filters
      cat_all: 'All',
      cat_love: 'Love',
      cat_friends: 'Friends',
      cat_spicy: 'Spicy',
      cat_deep: 'Deep',
      cat_work: 'Work',
      cat_culture: 'Culture',
      cat_lifestyle: 'Lifestyle',
      cat_self: 'Self',
      // Collections
      packs_collections: 'collections',
      coll_decks: 'decks',
      coll_date_night: 'Date Night',
      coll_desc_date_night: 'the perfect bundle for couples who want to go deeper',
      coll_spicy_edition: 'Spicy Edition',
      coll_desc_spicy_edition: 'hot takes, red flags & chaos — all in one pack',
      coll_deep_bonds: 'Deep Bonds',
      coll_desc_deep_bonds: 'meaningful conversations that actually matter',
      coll_friend_zone: 'Friend Zone',
      coll_desc_friend_zone: 'fun & real talk for you and your bestie',
      coll_culture_taste: 'Culture & Taste',
      coll_desc_culture_taste: 'travel, beliefs & lifestyle — how aligned are you?',
      coll_know_your_partner: 'Know Your Partner',
      coll_desc_know_your_partner: 'archetype quizzes to take about your partner & share',
      coll_know_yourself: 'Know Yourself',
      coll_desc_know_yourself: 'personality, shadow, boundaries — the full inner deep dive',
      coll_love_decoded: 'Love Decoded',
      coll_desc_love_decoded: 'attachment, love language & your relationship patterns',
      coll_relationship_xray: 'Relationship X-Ray',
      coll_desc_relationship_xray: 'see through the dynamics — couple story, hidden truths & more',
      coll_inner_work: 'Inner Work',
      coll_desc_inner_work: 'stress, sabotage & shadow — the hard stuff that heals',
      // Solo packs
      pack_attachment: 'Attachment Style',
      pack_innermirror: 'Inner Mirror',
      pack_stresstype: 'Stress Response',
      pack_count_attachment: '10 questions · how you love',
      pack_count_innermirror: '10 questions · who you really are',
      pack_count_stresstype: '10 questions · fight, flight, freeze or fawn',
      pack_desc_attachment: 'discover your attachment style. no partner needed.',
      pack_desc_innermirror: 'a mirror into your personality. just you.',
      // Solo results
      solo_badge: 'Solo',
      solo_your_result: 'your result',
      solo_dominant_trait: 'dominant trait',
      solo_breakdown: 'full breakdown',
      solo_take_another: 'take another test',
      solo_you_probably: 'you probably...',
      solo_note_to_self: 'note to self',
      mode_partner: 'Partner',
      mode_self: 'Self',
      // New solo packs
      pack_lovelang: 'Love Language',
      pack_shadow: 'Shadow Self',
      pack_emotionalage: 'Emotional Age',
      pack_boundaries: 'Boundary Check',
      pack_selfsabotage: 'Self-Sabotage',
      pack_count_lovelang: '10 questions · how you give & receive love',
      pack_count_shadow: '10 questions · what you hide from yourself',
      pack_count_emotionalage: '10 questions · how old is your inner self',
      pack_count_boundaries: '10 questions · walls, filters, or open doors',
      pack_count_selfsabotage: '10 questions · why you get in your own way',
      pack_desc_lovelang: 'based on the 5 love languages. warning: may cause feelings.',
      pack_desc_emotionalage: 'not your age — your emotional age. they\'re rarely the same.',
      // Character archetype decks
      pack_partnertype: 'Partner Archetype',
      pack_partnerera: 'Partner Era',
      pack_couplestory: 'Couple Story',
      pack_whattheyhide: 'What They Hide',
      pack_count_partnertype: '10 questions · what type is your person?',
      pack_count_partnerera: '10 questions · what era are you in?',
      pack_count_couplestory: '10 questions · your couple dynamic',
      pack_count_whattheyhide: '10 questions · unspoken truths',
      pack_desc_partnertype: 'golden retriever or chaos agent? find out their archetype.',
      pack_desc_partnerera: 'main character, healer, ride or die, or soft villain?',
      pack_desc_couplestory: 'soulmates, adventure duo, chaos couple, or slow burn?',
      pack_desc_whattheyhide: 'the things they feel but never say out loud.',
      // Blind Guess packs
      pack_flirtguess: 'Flirt & Guess',
      pack_desirematch: 'Desire Match',
      pack_count_flirtguess: '10 questions · answer + predict',
      pack_count_desirematch: '10 questions · answer + predict',
      pack_desc_flirtguess: 'answer honestly. then guess what they said. dare you?',
      pack_desc_desirematch: 'what you want vs what they want. how well do you really know?',
      coll_blind_guess: 'Blind Guess',
      coll_desc_blind_guess: 'answer for yourself, then predict your partner. double the reveal.',
      // Blind Guess UI
      blindguess_own_label: 'your answer',
      blindguess_guess_label: 'now guess their answer',
      blindguess_yours: 'yours',
      blindguess_you_guessed: 'you guessed',
      blindguess_you_guessed_them: 'you guessed for',
      blindguess_guessed_for_you: 'guessed for you',
      blindguess_actual: 'actual',
      blindguess_guessed: 'guessed',
      blindguess_read_score: 'read them right',
      blindguess_you_read_them: 'you read them',
      blindguess_they_read_you: 'they read you',
      // Badges
      badge_trending: 'Trending',
      badge_viral: 'Viral',
      badge_hot: 'Hot',
      badge_new: 'New',
      badge_popular: 'Popular',
      'badge_new-badge': 'New',
      // Marquee
      marquee_trending: 'Trending now',
      marquee_plays: '50k+ rounds played',
      marquee_new: '3 new packs',
      marquee_dare: 'dare to be honest?',
      marquee_viral: 'Going viral',
      marquee_send: 'send it to your person',
      // Invite
      invite_title: 'share with your person',
      invite_desc: 'they\'ll get the same questions. no one sees answers until you both finish.',
      invite_copy: 'copy',
      invite_simulate: 'simulate: partner joins →',
      // Quiz
      quiz_back: 'back',
      quiz_next: 'next',
      quiz_submit: 'submit',
      quiz_question: 'question',
      bubble_hint: 'tap all that apply',
      swipe_hint: 'pick all that fit',
      eliminate_hint: 'tap to eliminate \u2014 last one wins',
      // Waiting
      waiting_title: 'you\'re locked in 🔒',
      waiting_desc: 'waiting for <strong style="color:var(--text)">Alex</strong> to finish answering...',
      waiting_progress: 'Alex is on question 3 of 5',
      waiting_nudge: '👉 send a nudge',
      waiting_simulate: 'simulate: partner done →',
      // Modal
      modal_title: 'lock in your answers?',
      modal_desc: 'once you submit, no take-backs. your person will be notified you\'re done.',
      modal_confirm: 'lock it in',
      modal_cancel: 'wait, go back',
      // Settings
      settings_mode: 'Mode',
      settings_accent: 'Accent Color',
      // Results
      results_matches: 'matches',
      results_plot_twists: 'plot twists',
      results_sync_rate: 'sync rate',
      results_share: '📤 share this vibe check',
      results_play_another: 'play another pack',
      results_back_home: 'back home',
      results_you: 'you',
      results_of: 'of',
      // Reveal
      reveal_question_of: 'question {n} of {total}',
      reveal_you: 'You',
      reveal_tap_reveal: 'tap to reveal',
      reveal_tap_continue: 'tap to continue →',
      reveal_get_ready: 'get ready',
      // Feedback
      feedback_copied: 'copied!',
      feedback_nudge_sent: '✅ nudge sent!',
      feedback_link_copied: '✅ link copied!',
      // Delete
      delete_title: 'remove this session?',
      delete_desc: 'this will remove the session from your list. this can\'t be undone.',
      delete_confirm: 'remove',
      delete_cancel: 'cancel',
      delete_label: 'Delete',
      // Auth
      auth_pick_username: 'pick a username',
      auth_pick_subtitle: 'just a name so your partner knows it\'s you',
      auth_continue: 'continue',
      auth_welcome_back: 'welcome back',
      auth_sign_in: 'sign in',
      auth_back: 'back',
      auth_create_account_title: 'create your account',
      auth_create_account: 'create account',
      auth_signing_in: 'signing in as {name}',
      auth_nice_to_meet: 'nice to meet you, {name}',
      auth_enter_password: 'enter your password',
      auth_password_min_chars: 'password must be at least 4 characters',
      auth_passwords_no_match: 'passwords don\'t match',
      auth_password_placeholder: 'your password...',
      auth_create_password_placeholder: 'create a password...',
      auth_confirm_password_placeholder: 'confirm password...',
      // Waiting (dynamic)
      waiting_default_desc: 'waiting for your partner to finish answering...',
      waiting_checking: 'checking...',
      waiting_share_code: 'share this code with your partner:',
      waiting_copy_link: 'copy link',
      waiting_for_partner_named: 'waiting for {name} to finish answering...',
      waiting_for_partner_join: 'waiting for your partner to join and answer...',
      waiting_both_done: 'both done!',
      waiting_partner_done: 'partner is done! waiting for you...',
      waiting_answering: '{name} is answering...',
      waiting_partner: 'partner',
      waiting_submit_error: 'Could not submit answers. Check your connection and try again.',
      // Save account
      save_title: 'keep your account?',
      save_desc: 'set a password so you can come back, see your history, and start new sessions anytime.',
      save_confirm: 'save account',
      save_skip: 'skip for now',
      // Settings
      settings_dark: '🌙 Dark',
      settings_light: '☀️ Light',
      // Invite
      invite_start: 'start answering →',
      // Results loading
      results_loading: 'loading results...',
      results_load_error: 'could not load results',
      // Vibe labels
      vibe_0_title: 'Wildly Different',
      vibe_0_desc: 'opposites attract...right?',
      vibe_0_intro: 'Well, this was... <strong>eventful</strong>. You two see the world through very different lenses — and honestly, that might be the most interesting part.',
      vibe_20_title: 'Unpredictable Duo',
      vibe_20_desc: 'never a boring moment',
      vibe_20_intro: 'You two are <strong>unpredictable</strong> in the best way. Not always on the same page, but always an interesting read.',
      vibe_40_title: 'Getting There',
      vibe_40_desc: 'common ground exists',
      vibe_40_intro: 'There\'s real <strong>overlap</strong> here — and where there isn\'t, there\'s curiosity. That counts for a lot.',
      vibe_60_title: 'Real Ones',
      vibe_60_desc: 'you get each other',
      vibe_60_intro: 'You two <strong>get each other</strong>. Not perfectly, not always — but more than most. And the differences? That\'s where the good conversations live.',
      vibe_80_title: 'Mind Readers',
      vibe_80_desc: 'basically the same person',
      vibe_80_intro: 'OK this is getting <strong>suspicious</strong>. You two are answering like you share a brain. Who copied who?',
      vibe_100_title: 'Literally Telepathic',
      vibe_100_desc: 'this is actually scary',
      vibe_100_intro: '<strong>Every. Single. One.</strong> You matched on all of them. This is either beautiful or terrifying. Probably both.',
    },

    tr: {
      splash_tagline: 'aynı sorular. gizli cevaplar. bir açılış.',
      splash_get_started: 'başla',
      splash_have_account: 'hesabım var',
      guest_invited: 'davetlisiniz! 🎉',
      guest_title: 'oyuna katıl',
      guest_subtitle: 'oynamaya başlamak için bir isim girin',
      guest_placeholder: 'adınız...',
      guest_play: 'misafir olarak oyna',
      guest_have_account: 'hesabım var',
      guest_error_min_chars: 'en az 2 karakter',
      guest_error_connection: 'bağlantı hatası, tekrar deneyin',
      onboarding_title: 'nasıl çalışır',
      onboarding_step1_title: 'bir paket seç',
      onboarding_step1_desc: 'tarzına uyan bir soru paketi seç',
      onboarding_step2_title: 'gizlice cevapla',
      onboarding_step2_desc: 'ikiniz de aynı soruları cevaplıyorsunuz — gözetleme yok',
      onboarding_step3_title: 'birlikte aç',
      onboarding_step3_desc: 'cevaplar ancak ikiniz de gönderdikten sonra açılır',
      onboarding_cta: 'hadi başlayalım',
      home_all: 'Tümü',
      home_active: 'Aktif',
      home_completed: 'Tamamlanan',
      home_invite_sent: 'davet gönderildi',
      home_new_session: '+ yeni oturum',
      home_loading: 'yükleniyor...',
      home_no_sessions: 'henüz oturum yok — bir tane başlat!',
      home_with: 'ile',
      home_waiting_partner: 'partner bekleniyor',
      home_done: 'tamamlandı',
      home_load_error: 'oturumlar yüklenemedi',
      home_show_more: 'Daha fazla göster',
      home_with_alex: 'Alex ile',
      home_with_jordan: 'Jordan ile',
      home_with_taylor_match: 'Taylor ile · %83 eşleşme',
      badge_reveal: 'Aç!',
      badge_progress: 'Devam ediyor',
      badge_waiting: 'Bekliyor',
      pack_couples: 'Çiftler Paketi',
      pack_bestfriends: 'En İyi Arkadaşlar',
      pack_deeptalk: 'Derin Sohbet',
      pack_coworkers: 'İş Arkadaşları',
      pack_36questions: 'Aşık Olmak İçin 36 Soru',
      pack_friendship_deep_dive: 'Arkadaşlık Analizi',
      pack_count_couples: '10 soru',
      pack_count_bestfriends: '10 soru',
      pack_count_deeptalk: '10 soru',
      pack_count_coworkers: '10 soru',
      pack_count_36questions: '36 soru · Arthur Aron\'un çalışmasına dayanır',
      pack_hottakes: 'Keskin Yorumlar',
      pack_redflags: 'Red Flag mı Değil mi',
      pack_chaotic: 'Kaotik Enerji',
      pack_count_hottakes: '10 soru · sadece cesur fikirler',
      pack_count_redflags: '10 soru · yargıla rahatça',
      pack_count_chaotic: '10 soru · çılgın vibes',
      pack_fungames: 'Eğlence & Oyunlar',
      pack_worldtaste: 'Dünya & Lezzetler',
      pack_ethics: 'Etik & İkilemler',
      pack_situations: 'Durumlar',
      pack_livingtogether: 'Birlikte Yaşam',
      pack_soulspirit: 'Ruh & Mana',
      pack_count_fungames: '10 soru · hafif eğlence',
      pack_count_worldtaste: '10 soru · kültür & tatlar',
      pack_count_ethics: '10 soru · ahlaki kavşaklar',
      pack_count_situations: '10 soru · hayata tepki ver',
      pack_count_livingtogether: '10 soru · ev arkadaşlığı',
      pack_count_soulspirit: '10 soru · anlam & inanç',
      pack_desc_fungames: 'hafif kaos. yanlış cevap yok.',
      pack_desc_worldtaste: 'seyahat, yemek, kültür — ne kadar dünya vatandaşısın?',
      pack_desc_situations: 'gerçek hayat anları. gerçekten nasıl tepki verirdin?',
      nav_home: 'Ana Sayfa',
      nav_packs: 'Paketler',
      packs_subtitle: 'birini seç, gönder, neler olacak gör',
      packs_trending: 'şu an trend',
      packs_all: 'tüm paketler',
      packs_played: 'oynandı',
      pack_desc_36questions: 'yabancıları aşık eden viral çalışma. cesaret eder misin?',
      pack_desc_hottakes: 'sadece keskin fikirler. çit üstü yok.',
      pack_desc_redflags: 'birbirinizi yargılayın. merhamet yok.',
      cat_all: 'Tümü',
      cat_love: 'Aşk',
      cat_friends: 'Arkadaş',
      cat_spicy: 'Ateşli',
      cat_deep: 'Derin',
      cat_work: 'İş',
      cat_culture: 'Kültür',
      cat_lifestyle: 'Yaşam',
      cat_self: 'Kendin',
      packs_collections: 'koleksiyonlar',
      coll_decks: 'deste',
      coll_date_night: 'Randevu Gecesi',
      coll_desc_date_night: 'derinleşmek isteyen çiftler için mükemmel paket',
      coll_spicy_edition: 'Acı Versiyon',
      coll_desc_spicy_edition: 'hot take, red flag & kaos — hepsi bir arada',
      coll_deep_bonds: 'Derin Bağlar',
      coll_desc_deep_bonds: 'gerçekten önemli olan anlamlı sohbetler',
      coll_friend_zone: 'Arkadaş Bölgesi',
      coll_desc_friend_zone: 'sen ve en yakın arkadaşın için eğlence & gerçek konuşma',
      coll_culture_taste: 'Kültür & Zevk',
      coll_desc_culture_taste: 'seyahat, inançlar & yaşam tarzı — ne kadar uyumlusunuz?',
      coll_know_your_partner: 'Partnerini Tanı',
      coll_desc_know_your_partner: 'partneriniz hakkında çözüp paylaşacağınız arketip testleri',
      coll_know_yourself: 'Kendini Tanı',
      coll_desc_know_yourself: 'kişilik, gölge, sınırlar — tam bir iç keşif',
      coll_love_decoded: 'Aşk Çözümlendi',
      coll_desc_love_decoded: 'bağlanma, aşk dili & ilişki kalıpların',
      coll_relationship_xray: 'İlişki Röntgeni',
      coll_desc_relationship_xray: 'dinamikleri gör — çift hikayesi, gizli gerçekler & daha fazlası',
      coll_inner_work: 'İç Çalışma',
      coll_desc_inner_work: 'stres, sabotaj & gölge — iyileştiren zor şeyler',
      pack_attachment: 'Bağlanma Stili',
      pack_innermirror: 'İç Ayna',
      pack_stresstype: 'Stres Tepkisi',
      pack_count_attachment: '10 soru · nasıl seviyorsun',
      pack_count_innermirror: '10 soru · gerçekte kim olduğun',
      pack_count_stresstype: '10 soru · savaş, kaç, don veya uy',
      pack_desc_attachment: 'bağlanma stilini keşfet. partner gerekmiyor.',
      pack_desc_innermirror: 'kişiliğine bir ayna. sadece sen.',
      solo_badge: 'Solo',
      solo_your_result: 'sonucun',
      solo_dominant_trait: 'baskın özellik',
      solo_breakdown: 'tam analiz',
      solo_take_another: 'başka test yap',
      solo_you_probably: 'muhtemelen sen...',
      solo_note_to_self: 'kendine not',
      mode_partner: 'Partner',
      mode_self: 'Kendin',
      pack_lovelang: 'Sevgi Dili',
      pack_shadow: 'Gölge Ben',
      pack_emotionalage: 'Duygusal Yaş',
      pack_boundaries: 'Sınır Kontrolü',
      pack_selfsabotage: 'Kendini Sabote',
      pack_count_lovelang: '10 soru · nasıl seviyorsun',
      pack_count_shadow: '10 soru · kendinden sakladıkların',
      pack_count_emotionalage: '10 soru · iç dünyanın yaşı',
      pack_count_boundaries: '10 soru · duvarlar, filtreler, açık kapılar',
      pack_count_selfsabotage: '10 soru · neden kendi önüne geçiyorsun',
      pack_desc_lovelang: '5 sevgi diline dayalı. uyarı: duygulara neden olabilir.',
      pack_desc_emotionalage: 'yaşın değil — duygusal yaşın. nadiren aynıdır.',
      pack_partnertype: 'Partner Arketipi',
      pack_partnerera: 'Partner Dönemi',
      pack_couplestory: 'Çift Hikayesi',
      pack_whattheyhide: 'Sakladıkları',
      pack_count_partnertype: '10 soru · partnerin hangi tip?',
      pack_count_partnerera: '10 soru · hangi dönemdesin?',
      pack_count_couplestory: '10 soru · çift dinamiğiniz',
      pack_count_whattheyhide: '10 soru · söylenmeyen gerçekler',
      pack_desc_partnertype: 'golden retriever mı kaos ajanı mı? arketipini keşfet.',
      pack_desc_partnerera: 'ana karakter, şifacı, ölümüne sadık, yoksa yumuşak kötü?',
      pack_desc_couplestory: 'ruh eşleri, macera ikilisi, kaos çifti, yoksa yavaş yanan aşk?',
      pack_desc_whattheyhide: 'hissedip hiç söylemedikleri şeyler.',
      pack_flirtguess: 'Flört & Tahmin',
      pack_desirematch: 'Arzu Eşleşmesi',
      pack_count_flirtguess: '10 soru · cevapla + tahmin et',
      pack_count_desirematch: '10 soru · cevapla + tahmin et',
      pack_desc_flirtguess: 'dürüstçe cevapla. sonra onun ne dediğini tahmin et.',
      pack_desc_desirematch: 'senin istediğin vs onun istediği. gerçekten ne kadar tanıyorsun?',
      coll_blind_guess: 'Kör Tahmin',
      coll_desc_blind_guess: 'kendin cevapla, sonra partnerini tahmin et. çift açılış.',
      blindguess_own_label: 'senin cevabın',
      blindguess_guess_label: 'şimdi onun cevabını tahmin et',
      blindguess_yours: 'senin',
      blindguess_you_guessed: 'tahmin ettin',
      blindguess_you_guessed_them: 'tahminin',
      blindguess_guessed_for_you: 'senin için tahmin etti',
      blindguess_actual: 'gerçek',
      blindguess_guessed: 'tahmin etti',
      blindguess_read_score: 'doğru okudu',
      blindguess_you_read_them: 'sen onu okudun',
      blindguess_they_read_you: 'o seni okudu',
      badge_trending: 'Trend',
      badge_viral: 'Viral',
      badge_hot: 'Popüler',
      badge_new: 'Yeni',
      badge_popular: 'Sevilen',
      'badge_new-badge': 'Yeni',
      marquee_trending: 'Şu an trend',
      marquee_plays: '50k+ tur oynandı',
      marquee_new: '3 yeni paket',
      marquee_dare: 'dürüst olmaya cesaretin var mı?',
      marquee_viral: 'Viral oluyor',
      marquee_send: 'kişine gönder',
      invite_title: 'kişinle paylaş',
      invite_desc: 'aynı soruları alacak. ikiniz de bitirene kadar kimse cevapları göremez.',
      invite_copy: 'kopyala',
      invite_simulate: 'simülasyon: partner katılıyor →',
      quiz_back: 'geri',
      quiz_next: 'ileri',
      quiz_submit: 'gönder',
      quiz_question: 'soru',
      bubble_hint: 'uygun olanların hepsine dokun',
      swipe_hint: 'uyanların hepsini seç',
      eliminate_hint: 'elemek için dokun \u2014 son kalan kazanır',
      waiting_title: 'kilitlendin 🔒',
      waiting_desc: '<strong style="color:var(--text)">Alex</strong>\'in cevaplaması bekleniyor...',
      waiting_progress: 'Alex 5 sorudan 3. soruda',
      waiting_nudge: '👉 dürt',
      waiting_simulate: 'simülasyon: partner bitti →',
      modal_title: 'cevaplarını kilitle?',
      modal_desc: 'gönderdikten sonra geri dönüş yok. kişine bildirim gidecek.',
      modal_confirm: 'kilitle',
      modal_cancel: 'dur, geri dön',
      settings_mode: 'Mod',
      settings_accent: 'Vurgu Rengi',
      results_matches: 'eşleşme',
      results_plot_twists: 'sürpriz',
      results_sync_rate: 'uyum oranı',
      results_share: '📤 vibe check\'i paylaş',
      results_play_another: 'başka paket oyna',
      results_back_home: 'ana sayfaya dön',
      results_you: 'sen',
      results_of: '/',
      reveal_question_of: 'soru {n} / {total}',
      reveal_you: 'Sen',
      reveal_tap_reveal: 'açmak için dokun',
      reveal_tap_continue: 'devam için dokun →',
      reveal_get_ready: 'hazır ol',
      feedback_copied: 'kopyalandı!',
      feedback_nudge_sent: '✅ dürtü gönderildi!',
      feedback_link_copied: '✅ link kopyalandı!',
      delete_title: 'bu oturumu kaldır?',
      delete_desc: 'bu oturumu listenden kaldıracak. bu işlem geri alınamaz.',
      delete_confirm: 'kaldır',
      delete_cancel: 'iptal',
      delete_label: 'Sil',
      auth_pick_username: 'kullanıcı adı seç',
      auth_pick_subtitle: 'partnerinin seni tanıması için bir isim yeter',
      auth_continue: 'devam',
      auth_welcome_back: 'tekrar hoş geldin',
      auth_sign_in: 'giriş yap',
      auth_back: 'geri',
      auth_create_account_title: 'hesabını oluştur',
      auth_create_account: 'hesap oluştur',
      auth_signing_in: '{name} olarak giriş yapılıyor',
      auth_nice_to_meet: 'tanıştığımıza memnunum, {name}',
      auth_enter_password: 'şifreni gir',
      auth_password_min_chars: 'şifre en az 4 karakter olmalı',
      auth_passwords_no_match: 'şifreler eşleşmiyor',
      auth_password_placeholder: 'şifren...',
      auth_create_password_placeholder: 'şifre oluştur...',
      auth_confirm_password_placeholder: 'şifreyi onayla...',
      waiting_default_desc: 'partnerinin cevaplarını bitirmesi bekleniyor...',
      waiting_checking: 'kontrol ediliyor...',
      waiting_share_code: 'bu kodu partnerinle paylaş:',
      waiting_copy_link: 'linki kopyala',
      waiting_for_partner_named: '{name} cevaplarını bitirsin diye bekleniyor...',
      waiting_for_partner_join: 'partnerinin katılması ve cevap vermesi bekleniyor...',
      waiting_both_done: 'ikisi de bitti!',
      waiting_partner_done: 'partner bitti! seni bekliyor...',
      waiting_answering: '{name} cevaplıyor...',
      waiting_partner: 'partner',
      waiting_submit_error: 'Cevaplar gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.',
      save_title: 'hesabını sakla?',
      save_desc: 'geri dönebilmek, geçmişini görebilmek ve yeni oturumlar başlatabilmek için bir şifre belirle.',
      save_confirm: 'hesabı kaydet',
      save_skip: 'şimdilik geç',
      settings_dark: '🌙 Koyu',
      settings_light: '☀️ Açık',
      invite_start: 'cevaplamaya başla →',
      results_loading: 'sonuçlar yükleniyor...',
      results_load_error: 'sonuçlar yüklenemedi',
      vibe_0_title: 'Bambaşka',
      vibe_0_desc: 'zıtlar birbirini çeker...değil mi?',
      vibe_0_intro: 'Şey, bu... <strong>hareketliydi</strong>. İkiniz dünyaya çok farklı açılardan bakıyorsunuz — ve açıkçası, en ilginç kısmı bu olabilir.',
      vibe_20_title: 'Tahmin Edilemez İkili',
      vibe_20_desc: 'asla sıkıcı bir an yok',
      vibe_20_intro: 'İkiniz en iyi şekilde <strong>öngörülemezsiniz</strong>. Her zaman aynı sayfada değilsiniz ama her zaman ilginç bir okuma.',
      vibe_40_title: 'Yolda',
      vibe_40_desc: 'ortak nokta var',
      vibe_40_intro: 'Burada gerçek bir <strong>örtüşme</strong> var — ve olmayan yerde merak var. Bu çok şey ifade ediyor.',
      vibe_60_title: 'Gerçek Olanlar',
      vibe_60_desc: 'birbirinizi anlıyorsunuz',
      vibe_60_intro: 'İkiniz <strong>birbirinizi anlıyorsunuz</strong>. Mükemmel değil, her zaman değil — ama çoğundan fazla. Farklar mı? İyi sohbetlerin yaşandığı yer orası.',
      vibe_80_title: 'Zihin Okuyucular',
      vibe_80_desc: 'aynı kişi gibisiniz',
      vibe_80_intro: 'Tamam bu <strong>şüpheli</strong> olmaya başladı. İkiniz aynı beyni paylaşıyormuşsunuz gibi cevaplıyorsunuz. Kim kimden kopya çekti?',
      vibe_100_title: 'Tam Telepati',
      vibe_100_desc: 'bu gerçekten korkutucu',
      vibe_100_intro: '<strong>Her. Bir. Tanesi.</strong> Hepsinde eşleştiniz. Bu ya güzel ya da korkutucu. Muhtemelen ikisi de.',
    },

    th: {
      splash_tagline: 'คำถามเดียวกัน คำตอบลับ เปิดเผยพร้อมกัน',
      splash_get_started: 'เริ่มเลย',
      splash_have_account: 'ฉันมีบัญชีแล้ว',
      guest_invited: 'คุณได้รับเชิญ! 🎉',
      guest_title: 'เข้าร่วมเกม',
      guest_subtitle: 'ใส่ชื่อเพื่อเริ่มเล่น',
      guest_placeholder: 'ชื่อของคุณ...',
      guest_play: 'เล่นในฐานะแขก',
      guest_have_account: 'ฉันมีบัญชีแล้ว',
      guest_error_min_chars: 'อย่างน้อย 2 ตัวอักษร',
      guest_error_connection: 'เชื่อมต่อผิดพลาด ลองอีกครั้ง',
      onboarding_title: 'วิธีใช้งาน',
      onboarding_step1_title: 'เลือกชุดคำถาม',
      onboarding_step1_desc: 'เลือกชุดคำถามที่เข้ากับคุณ',
      onboarding_step2_title: 'ตอบแบบส่วนตัว',
      onboarding_step2_desc: 'ทั้งคู่ตอบคำถามเดียวกัน — ห้ามแอบดู',
      onboarding_step3_title: 'เปิดเผยด้วยกัน',
      onboarding_step3_desc: 'คำตอบจะเปิดเผยเมื่อทั้งสองคนส่งแล้วเท่านั้น',
      onboarding_cta: 'เริ่มเลย',
      home_all: 'ทั้งหมด',
      home_active: 'กำลังดำเนินการ',
      home_completed: 'เสร็จสิ้น',
      home_invite_sent: 'ส่งคำเชิญแล้ว',
      home_new_session: '+ เซสชันใหม่',
      home_loading: 'กำลังโหลด...',
      home_no_sessions: 'ยังไม่มีเซสชัน — เริ่มเลย!',
      home_with: 'กับ',
      home_waiting_partner: 'รอคู่หู',
      home_done: 'เสร็จแล้ว',
      home_load_error: 'ไม่สามารถโหลดเซสชันได้',
      home_show_more: 'แสดงเพิ่มเติม',
      home_with_alex: 'กับ Alex',
      home_with_jordan: 'กับ Jordan',
      home_with_taylor_match: 'กับ Taylor · ตรงกัน 83%',
      badge_reveal: 'เปิดเผย!',
      badge_progress: 'กำลังทำ',
      badge_waiting: 'รอ',
      pack_couples: 'คู่รัก',
      pack_bestfriends: 'เพื่อนซี้',
      pack_deeptalk: 'คุยลึก',
      pack_coworkers: 'เพื่อนร่วมงาน',
      pack_36questions: '36 คำถามเพื่อตกหลุมรัก',
      pack_friendship_deep_dive: 'เจาะลึกมิตรภาพ',
      pack_count_couples: '10 คำถาม',
      pack_count_bestfriends: '10 คำถาม',
      pack_count_deeptalk: '10 คำถาม',
      pack_count_coworkers: '10 คำถาม',
      pack_count_36questions: '36 คำถาม · อ้างอิงจากงานวิจัยของ Arthur Aron',
      pack_hottakes: 'ความเห็นแรง',
      pack_redflags: 'Red Flag หรือเปล่า',
      pack_chaotic: 'พลังวุ่นวาย',
      pack_count_hottakes: '10 คำถาม · ความเห็นแบบจัดจ้าน',
      pack_count_redflags: '10 คำถาม · ตัดสินได้เลย',
      pack_count_chaotic: '10 คำถาม · ไวบ์บ้าบอ',
      pack_fungames: 'สนุก & เกม',
      pack_worldtaste: 'โลก & รสชาติ',
      pack_ethics: 'จริยธรรม & ทางเลือก',
      pack_situations: 'สถานการณ์',
      pack_livingtogether: 'อยู่ด้วยกัน',
      pack_soulspirit: 'จิตวิญญาณ',
      pack_count_fungames: '10 คำถาม · สนุกเบาๆ',
      pack_count_worldtaste: '10 คำถาม · วัฒนธรรม & รสชาติ',
      pack_count_ethics: '10 คำถาม · ทางแยกศีลธรรม',
      pack_count_situations: '10 คำถาม · ตอบสนองต่อชีวิต',
      pack_count_livingtogether: '10 คำถาม · ชีวิตร่วมกัน',
      pack_count_soulspirit: '10 คำถาม · ความหมาย & ความเชื่อ',
      pack_desc_fungames: 'ความวุ่นวายเบาๆ ไม่มีคำตอบผิด',
      pack_desc_worldtaste: 'ท่องเที่ยว อาหาร วัฒนธรรม — คุณรู้จักโลกแค่ไหน?',
      pack_desc_situations: 'ช่วงเวลาในชีวิตจริง คุณจะตอบสนองยังไง?',
      nav_home: 'หน้าแรก',
      nav_packs: 'ชุดคำถาม',
      packs_subtitle: 'เลือกชุด ส่งไป แล้วดูผลลัพธ์',
      packs_trending: 'กำลังฮิต',
      packs_all: 'ชุดทั้งหมด',
      packs_played: 'เล่นแล้ว',
      pack_desc_36questions: 'งานวิจัยไวรัลที่ทำให้คนแปลกหน้าตกหลุมรัก กล้าไหม?',
      pack_desc_hottakes: 'ความเห็นแบบจัดจ้านเท่านั้น ห้ามอยู่กลางๆ',
      pack_desc_redflags: 'ตัดสินกันเลย ไม่ต้องเกรงใจ',
      cat_all: 'ทั้งหมด',
      cat_love: 'รัก',
      cat_friends: 'เพื่อน',
      cat_spicy: 'แซ่บ',
      cat_deep: 'ลึก',
      cat_work: 'งาน',
      cat_culture: 'วัฒนธรรม',
      cat_lifestyle: 'ไลฟ์สไตล์',
      cat_self: 'ตัวเอง',
      packs_collections: 'คอลเลกชัน',
      coll_decks: 'สำรับ',
      coll_date_night: 'คืนเดท',
      coll_desc_date_night: 'แพ็กสมบูรณ์แบบสำหรับคู่รักที่อยากรู้จักกันลึกขึ้น',
      coll_spicy_edition: 'เผ็ดร้อน',
      coll_desc_spicy_edition: 'ความเห็นแรง ธงแดง & ความวุ่นวาย — ครบในแพ็กเดียว',
      coll_deep_bonds: 'สายสัมพันธ์ลึก',
      coll_desc_deep_bonds: 'บทสนทนาที่มีความหมายจริงๆ',
      coll_friend_zone: 'โซนเพื่อน',
      coll_desc_friend_zone: 'สนุก & คุยจริงจังกับเพื่อนซี้',
      coll_culture_taste: 'วัฒนธรรม & รสนิยม',
      coll_desc_culture_taste: 'เที่ยว ความเชื่อ & ไลฟ์สไตล์ — เข้ากันแค่ไหน?',
      coll_know_your_partner: 'รู้จักคนรัก',
      coll_desc_know_your_partner: 'แบบทดสอบอาร์คีไทป์เกี่ยวกับคนรักของคุณ & แชร์ผล',
      coll_know_yourself: 'รู้จักตัวเอง',
      coll_desc_know_yourself: 'บุคลิกภาพ เงามืด ขอบเขต — ดำดิ่งสู่ภายในอย่างเต็มที่',
      coll_love_decoded: 'ถอดรหัสความรัก',
      coll_desc_love_decoded: 'ความผูกพัน ภาษารัก & รูปแบบความสัมพันธ์ของคุณ',
      coll_relationship_xray: 'เอ็กซ์เรย์ความสัมพันธ์',
      coll_desc_relationship_xray: 'มองทะลุพลวัต — เรื่องราวคู่ ความจริงที่ซ่อน & อีกมากมาย',
      coll_inner_work: 'งานภายใน',
      coll_desc_inner_work: 'ความเครียด การทำลายตัวเอง & เงามืด — สิ่งยากที่เยียวยา',
      pack_attachment: 'สไตล์ความผูกพัน',
      pack_innermirror: 'กระจกภายใน',
      pack_stresstype: 'การตอบสนองต่อความเครียด',
      pack_count_attachment: '10 คำถาม · คุณรักแบบไหน',
      pack_count_innermirror: '10 คำถาม · ตัวตนที่แท้จริง',
      pack_count_stresstype: '10 คำถาม · สู้ หนี แข็ง หรือตาม',
      pack_desc_attachment: 'ค้นพบสไตล์ความผูกพัน ไม่ต้องมีคู่',
      pack_desc_innermirror: 'กระจกส่องบุคลิกภาพ แค่คุณ',
      solo_badge: 'เดี่ยว',
      solo_your_result: 'ผลลัพธ์ของคุณ',
      solo_dominant_trait: 'ลักษณะเด่น',
      solo_breakdown: 'วิเคราะห์ทั้งหมด',
      solo_take_another: 'ทำแบบทดสอบอื่น',
      solo_you_probably: 'คุณอาจจะ...',
      solo_note_to_self: 'โน้ตถึงตัวเอง',
      mode_partner: 'คู่หู',
      mode_self: 'ตัวเอง',
      pack_lovelang: 'ภาษารัก',
      pack_shadow: 'ตัวตนที่ซ่อน',
      pack_emotionalage: 'อายุทางอารมณ์',
      pack_boundaries: 'เช็คขอบเขต',
      pack_selfsabotage: 'ทำลายตัวเอง',
      pack_count_lovelang: '10 คำถาม · คุณให้และรับความรักยังไง',
      pack_count_shadow: '10 คำถาม · สิ่งที่ซ่อนจากตัวเอง',
      pack_count_emotionalage: '10 คำถาม · ตัวตนข้างในอายุเท่าไหร่',
      pack_count_boundaries: '10 คำถาม · กำแพง ฟิลเตอร์ หรือประตูเปิด',
      pack_count_selfsabotage: '10 คำถาม · ทำไมถึงขวางตัวเอง',
      pack_desc_lovelang: 'อิงจาก 5 ภาษารัก เตือน: อาจทำให้เกิดความรู้สึก',
      pack_desc_emotionalage: 'ไม่ใช่อายุคุณ — อายุทางอารมณ์ แทบไม่เคยเท่ากัน',
      pack_partnertype: 'อาร์คีไทป์คนรัก',
      pack_partnerera: 'ยุคคนรัก',
      pack_couplestory: 'เรื่องราวคู่รัก',
      pack_whattheyhide: 'สิ่งที่เขาซ่อน',
      pack_count_partnertype: '10 คำถาม · คนรักเป็นแบบไหน?',
      pack_count_partnerera: '10 คำถาม · คุณอยู่ในยุคไหน?',
      pack_count_couplestory: '10 คำถาม · ไดนามิกของคู่คุณ',
      pack_count_whattheyhide: '10 คำถาม · ความจริงที่ไม่เคยพูด',
      pack_desc_partnertype: 'โกลเด้นรีทรีฟเวอร์หรือตัวแทนแห่งความวุ่นวาย? ค้นหาอาร์คีไทป์คนรัก',
      pack_desc_partnerera: 'ตัวละครหลัก, ผู้เยียวยา, ตายด้วยกัน, หรือวายร้ายอ่อนโยน?',
      pack_desc_couplestory: 'เนื้อคู่, คู่ผจญภัย, คู่วุ่นวาย, หรือรักค่อยเป็นค่อยไป?',
      pack_desc_whattheyhide: 'สิ่งที่เขารู้สึกแต่ไม่เคยพูดออกมา',
      pack_flirtguess: 'จีบ & ทาย',
      pack_desirematch: 'จับคู่ความปรารถนา',
      pack_count_flirtguess: '10 คำถาม · ตอบ + ทาย',
      pack_count_desirematch: '10 คำถาม · ตอบ + ทาย',
      pack_desc_flirtguess: 'ตอบตามจริง แล้วทายว่าเขาตอบอะไร กล้าไหม?',
      pack_desc_desirematch: 'สิ่งที่คุณต้องการ vs สิ่งที่เขาต้องการ รู้จักกันดีแค่ไหน?',
      coll_blind_guess: 'ทายสุ่ม',
      coll_desc_blind_guess: 'ตอบเอง แล้วทายคนรัก เปิดเผยสองเท่า',
      blindguess_own_label: 'คำตอบของคุณ',
      blindguess_guess_label: 'ทายคำตอบของเขา',
      blindguess_yours: 'ของคุณ',
      blindguess_you_guessed: 'คุณทาย',
      blindguess_you_guessed_them: 'คุณทายให้',
      blindguess_guessed_for_you: 'ทายให้คุณ',
      blindguess_actual: 'จริงๆ',
      blindguess_guessed: 'ทาย',
      blindguess_read_score: 'อ่านถูก',
      blindguess_you_read_them: 'คุณอ่านเขา',
      blindguess_they_read_you: 'เขาอ่านคุณ',
      badge_trending: 'ฮิต',
      badge_viral: 'ไวรัล',
      badge_hot: 'ฮอต',
      badge_new: 'ใหม่',
      badge_popular: 'ยอดนิยม',
      'badge_new-badge': 'ใหม่',
      marquee_trending: 'กำลังฮิต',
      marquee_plays: '50k+ รอบที่เล่น',
      marquee_new: '3 ชุดใหม่',
      marquee_dare: 'กล้าพูดตรงไหม?',
      marquee_viral: 'กำลังไวรัล',
      marquee_send: 'ส่งให้คนของคุณ',
      invite_title: 'แชร์ให้คนของคุณ',
      invite_desc: 'พวกเขาจะได้คำถามเดียวกัน ไม่มีใครเห็นคำตอบจนกว่าทั้งคู่จะตอบเสร็จ',
      invite_copy: 'คัดลอก',
      invite_simulate: 'จำลอง: คู่หูเข้าร่วม →',
      quiz_back: 'กลับ',
      quiz_next: 'ถัดไป',
      quiz_submit: 'ส่ง',
      quiz_question: 'คำถาม',
      bubble_hint: 'แตะทุกข้อที่ตรง',
      swipe_hint: 'เลือกทุกข้อที่ใช่',
      eliminate_hint: 'แตะเพื่อตัดออก \u2014 ตัวสุดท้ายชนะ',
      waiting_title: 'คุณพร้อมแล้ว 🔒',
      waiting_desc: 'รอ <strong style="color:var(--text)">Alex</strong>...',
      waiting_progress: 'Alex ตอบถึงข้อ 3 จาก 5',
      waiting_nudge: '👉 เตือน',
      waiting_simulate: 'จำลอง: คู่หูตอบเสร็จ →',
      modal_title: 'ยืนยันคำตอบ?',
      modal_desc: 'เมื่อส่งแล้วจะแก้ไม่ได้ คู่หูของคุณจะได้รับแจ้ง',
      modal_confirm: 'ยืนยัน',
      modal_cancel: 'เดี๋ยวก่อน กลับไป',
      settings_mode: 'โหมด',
      settings_accent: 'สีเน้น',
      results_matches: 'ตรงกัน',
      results_plot_twists: 'เซอร์ไพรส์',
      results_sync_rate: 'อัตราซิงค์',
      results_share: '📤 แชร์ไวบ์เช็ค',
      results_play_another: 'เล่นชุดอื่น',
      results_back_home: 'กลับหน้าแรก',
      results_you: 'คุณ',
      results_of: 'จาก',
      reveal_question_of: 'คำถาม {n} จาก {total}',
      reveal_you: 'คุณ',
      reveal_tap_reveal: 'แตะเพื่อเปิดเผย',
      reveal_tap_continue: 'แตะเพื่อไปต่อ →',
      reveal_get_ready: 'เตรียมตัว',
      feedback_copied: 'คัดลอกแล้ว!',
      feedback_nudge_sent: '✅ เตือนแล้ว!',
      feedback_link_copied: '✅ คัดลอกลิงก์แล้ว!',
      delete_title: 'ลบเซสชันนี้?',
      delete_desc: 'เซสชันจะถูกลบออกจากรายการของคุณ ไม่สามารถย้อนกลับได้',
      delete_confirm: 'ลบ',
      delete_cancel: 'ยกเลิก',
      delete_label: 'ลบ',
      auth_pick_username: 'เลือกชื่อผู้ใช้',
      auth_pick_subtitle: 'แค่ชื่อเพื่อให้คู่ของคุณรู้ว่าเป็นคุณ',
      auth_continue: 'ดำเนินการต่อ',
      auth_welcome_back: 'ยินดีต้อนรับกลับ',
      auth_sign_in: 'เข้าสู่ระบบ',
      auth_back: 'กลับ',
      auth_create_account_title: 'สร้างบัญชีของคุณ',
      auth_create_account: 'สร้างบัญชี',
      auth_signing_in: 'กำลังเข้าสู่ระบบเป็น {name}',
      auth_nice_to_meet: 'ยินดีที่ได้รู้จัก, {name}',
      auth_enter_password: 'ใส่รหัสผ่านของคุณ',
      auth_password_min_chars: 'รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร',
      auth_passwords_no_match: 'รหัสผ่านไม่ตรงกัน',
      auth_password_placeholder: 'รหัสผ่านของคุณ...',
      auth_create_password_placeholder: 'สร้างรหัสผ่าน...',
      auth_confirm_password_placeholder: 'ยืนยันรหัสผ่าน...',
      waiting_default_desc: 'รอให้คู่ของคุณตอบคำถามเสร็จ...',
      waiting_checking: 'กำลังตรวจสอบ...',
      waiting_share_code: 'แชร์โค้ดนี้กับคู่ของคุณ:',
      waiting_copy_link: 'คัดลอกลิงก์',
      waiting_for_partner_named: 'รอให้ {name} ตอบคำถามเสร็จ...',
      waiting_for_partner_join: 'รอให้คู่ของคุณเข้าร่วมและตอบ...',
      waiting_both_done: 'ทั้งคู่เสร็จแล้ว!',
      waiting_partner_done: 'คู่ของคุณเสร็จแล้ว! รอคุณอยู่...',
      waiting_answering: '{name} กำลังตอบ...',
      waiting_partner: 'คู่หู',
      waiting_submit_error: 'ไม่สามารถส่งคำตอบได้ ตรวจสอบการเชื่อมต่อและลองอีกครั้ง',
      save_title: 'เก็บบัญชีไว้?',
      save_desc: 'ตั้งรหัสผ่านเพื่อกลับมาดูประวัติและเริ่มเซสชันใหม่ได้ทุกเมื่อ',
      save_confirm: 'บันทึกบัญชี',
      save_skip: 'ข้ามไปก่อน',
      settings_dark: '🌙 มืด',
      settings_light: '☀️ สว่าง',
      invite_start: 'เริ่มตอบ →',
      results_loading: 'กำลังโหลดผลลัพธ์...',
      results_load_error: 'ไม่สามารถโหลดผลลัพธ์ได้',
      vibe_0_title: 'แตกต่างสุดขั้ว',
      vibe_0_desc: 'ขั้วตรงข้ามดึงดูดกัน...ใช่ไหม?',
      vibe_0_intro: 'อืม นี่มัน... <strong>มีสีสัน</strong> คุณสองคนมองโลกผ่านเลนส์ที่ต่างกันมาก — แต่บอกตรงๆ นั่นอาจเป็นส่วนที่น่าสนใจที่สุด',
      vibe_20_title: 'คู่คาดเดาไม่ได้',
      vibe_20_desc: 'ไม่มีช่วงเวลาน่าเบื่อ',
      vibe_20_intro: 'คุณสองคน<strong>คาดเดาไม่ได้</strong>ในทางที่ดีที่สุด ไม่ได้อยู่หน้าเดียวกันเสมอ แต่น่าอ่านเสมอ',
      vibe_40_title: 'กำลังไปได้ดี',
      vibe_40_desc: 'มีจุดร่วม',
      vibe_40_intro: 'มี<strong>จุดร่วม</strong>จริงๆ ตรงนี้ — และตรงที่ไม่มี ก็มีความอยากรู้ นั่นมีค่ามาก',
      vibe_60_title: 'ตัวจริง',
      vibe_60_desc: 'เข้าใจกัน',
      vibe_60_intro: 'คุณสองคน<strong>เข้าใจกัน</strong> ไม่สมบูรณ์แบบ ไม่ใช่ทุกครั้ง — แต่มากกว่าคนส่วนใหญ่ ส่วนที่ต่าง? ตรงนั้นแหละที่บทสนทนาดีๆ เกิดขึ้น',
      vibe_80_title: 'อ่านใจได้',
      vibe_80_desc: 'เหมือนคนเดียวกัน',
      vibe_80_intro: 'โอเค นี่เริ่ม<strong>น่าสงสัย</strong>แล้ว คุณสองคนตอบเหมือนใช้สมองเดียวกัน ใครลอกใคร?',
      vibe_100_title: 'เทเลพาธีแท้',
      vibe_100_desc: 'น่ากลัวจริงๆ',
      vibe_100_intro: '<strong>ทุก. คำถาม. เลย.</strong> ตรงกันหมด นี่มันสวยงามหรือน่ากลัว อาจจะทั้งสองอย่าง',
    },
  },

  current: localStorage.getItem('bs-lang') || 'en',

  t(key) {
    return this.translations[this.current]?.[key]
      || this.translations.en[key]
      || key;
  },

  setLanguage(lang) {
    if (!this.translations[lang]) return;
    this.current = lang;
    localStorage.setItem('bs-lang', lang);
    document.documentElement.setAttribute('lang', lang);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === 'function') updateLangCycleBtn();
    // Re-render dynamic content
    if (typeof renderPacksGrid === 'function') renderPacksGrid();
    if (typeof renderHomeSessions === 'function' && currentScreen === 'home') renderHomeSessions();
    if (typeof getQuestions === 'function') {
      questions = getQuestions(selectedPackKey || 'couples');
    }
  },

  applyAll() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const val = this.t(key);
      if (el.innerHTML !== val) el.innerHTML = val;
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
      const key = el.getAttribute('data-i18n-placeholder');
      el.placeholder = this.t(key);
    });
  },

  renderSelector() {
    const html = Object.entries(this.languages).map(([code, { flag, label }]) =>
      `<button class="lang-btn ${code === this.current ? 'active' : ''}" onclick="i18n.setLanguage('${code}')">
        <span class="lang-flag">${flag}</span>${label}
      </button>`
    ).join('');
    document.querySelectorAll('.lang-selector').forEach(el => el.innerHTML = html);
  },

  init() {
    document.documentElement.setAttribute('lang', this.current);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === 'function') updateLangCycleBtn();
  }
};

function cycleLang() {
  const codes = Object.keys(i18n.languages);
  const idx = codes.indexOf(i18n.current);
  const next = codes[(idx + 1) % codes.length];
  i18n.setLanguage(next);
}

function updateLangCycleBtn() {
  const flag = document.getElementById('langCycleFlag');
  if (flag) flag.textContent = i18n.languages[i18n.current]?.flag || '🌐';
}
